#pragma once

// Generated by tools/ida_nightsharp_offset_dump_plugin.py
// Generated UTC: 2026-04-05T09:23:02+00:00
// Applied rules: 8
// Unresolved rules: 0

namespace Offset {

namespace GameObjectsRuntime {
    constexpr auto Player = 0x1DF65A8;   // 48 8B 05 ? ? ? ? 4C 8B DA 4C 8B C1 [signature was not learned into a strict rule]
    constexpr auto Objects = 0x1DBEF28;   // 48 8B 0D ? ? ? ? 48 8B 50 ? 8B 52 ? E8 ? ? ? ? 4C 8B F0 [signature was not learned into a strict rule]
    constexpr auto Heroes = 0x1DBEF80;   // 48 8B 05 ? ? ? ? 45 33 FF 49 89 73 ? [signature was not learned into a strict rule]
    constexpr auto Minions = 0x1DBEF78;   // 48 8B 0D ? ? ? ? E8 ? ? ? ? 33 FF 48 85 C0 [signature was not learned into a strict rule]
    constexpr auto Missiles = 0x1DC2DA0;   // 48 8B 1D ? ? ? ? 48 8D 94 24 ? ? ? ? 48 8D 4C 24 [signature was not learned into a strict rule]
    constexpr auto Turrets = 0x1DCBD00;   // 48 89 0D ? ? ? ? 48 8D 05 ? ? ? ? 33 D2 48 89 01 48 8B C1 [signature was not learned into a strict rule]
    constexpr auto UnderMouseObject = 0x1DC2FA0;   // 48 89 0D ? ? ? ? 48 8D 05 ? ? ? ? 48 89 01 33 D2 48 89 51 ? [signature was not learned into a strict rule]
} // namespace GameObjectsRuntime

namespace ObjectManagerRuntime {
    constexpr auto ManagerListItems = 0x8;
    constexpr auto ManagerListSize = 0x10;
    constexpr auto GetFirstObject = 0x9DF5D0;   // 40 53 48 83 EC ? 4C 8B 05 ? ? ? ? 0F B6 CA [signature was not learned into a strict rule]
    constexpr auto GetNextObject = 0x526CD0;   // 40 53 48 83 EC ? 48 8B 01 48 8B D9 FF 50 ? 48 81 C3 ? ? ? ? [signature was not learned into a strict rule]
    constexpr auto FindObject = 0x5259B0;   // 48 89 5C 24 ? 4C 89 44 24 ? 55 56 57 41 54 41 55 41 56 41 57 48 83 EC ? 4C 8B 29 [signature was not learned into a strict rule]
} // namespace ObjectManagerRuntime

namespace GameRuntime {
    constexpr auto GameTime = 0x1DCD1E0;   // F3 0F 5C 35 ? ? ? ? 0F 28 F8 [signature was not learned into a strict rule]
    constexpr auto NetInstance = 0x1DBEF20;   // 48 8B 05 ? ? ? ? 0F B6 15 ? ? ? ? 48 85 C0 41 0F 95 C1 48 85 C0 74 ? 44 0F B6 80 ? ? ? ? [signature was not learned into a strict rule]
    constexpr auto ChatClient = 0x1DD2A50;   // 48 89 05 ? ? ? ? E8 ? ? ? ? 48 8D 0D ? ? ? ? E8 ? ? ? ? 48 8D 05 ? ? ? ? 48 83 C4 28 C3 CC CC 4C 8B 49 [signature was not learned into a strict rule]
    constexpr auto ChatInstance = 0x1DC2FB0;   // 89 05 ? ? ? ? 89 05 ? ? ? ? F2 41 0F 10 45 ? [signature was not learned into a strict rule]
    constexpr auto ShopInstance = 0x1DD2A68;   // 48 8B 0D ? ? ? ? E8 ? ? ? ? 48 8B 0D ? ? ? ? E8 ? ? ? ? 48 8B 0D ? ? ? ? B2 ? [signature was not learned into a strict rule]
    constexpr auto OpenWindowsArray = 0x1E66E78;
    constexpr auto OpenWindowsCount = 0x1E66E80;
    constexpr auto MySpellState = 0x1DC5AF8;   // 48 8B 15 ? ? ? ? 85 DB 78 [signature was not learned into a strict rule]
    constexpr auto CursorPosRaw = 0x1E4F610;   // 48 89 1D ? ? ? ? 48 89 1D ? ? ? ? E8 ? ? ? ? 48 39 1D ? ? ? ? [signature was not learned into a strict rule]
    constexpr auto MouseScreenVec2 = 0x1DC2D48;   // 48 8B 0D ? ? ? ? E8 ? ? ? ? 48 8B C8 48 83 C4 ? [signature was not learned into a strict rule]
    constexpr auto GetPing = 0x673720;   // E8 ? ? ? ? 8B F8 39 03 [signature was not learned into a strict rule]
    constexpr auto GetMapID = 0x298FD0;   // E8 ? ? ? ? 48 8D 8F ? ? ? ? 89 47 ? [signature was not learned into a strict rule]
    constexpr auto PrintChat = 0x10CE620;   // E8 ? ? ? ? 48 83 C4 ? C3 CC CC CC CC CC CC 4C 8B DC 53 [signature was not learned into a strict rule]
} // namespace GameRuntime

namespace DrawingRuntime {
    constexpr auto WorldToScreen = 0x127E560;   // 48 8B C4 48 89 50 ? 55 53 48 8D 68 A1 [signature was not learned into a strict rule]
    constexpr auto HudInstance = 0x1DBF0C8;   // 48 8B 0D ? ? ? ? 8B 57 ? [signature was not learned into a strict rule]
    constexpr auto ViewPort = 0x1DD29E0;   // 48 8B 0D ? ? ? ? 48 8D 96 ? ? ? ? 48 8B 5C 24 ? [signature was not learned into a strict rule]
    constexpr auto ViewPort2 = 0x1E89F58;   // 48 C7 05 ? ? ? ? ? ? ? ? 48 8D 4B ? [signature was not learned into a strict rule]
    constexpr auto Renderer = 0x1E89F50;   // 48 8B 0D ? ? ? ? 48 8B 01 FF 50 ? 48 8B 08 41 B1 ? [signature was not learned into a strict rule]
    constexpr auto ViewProjOffset = 0x1E76200;   // 48 8D 0D ? ? ? ? E8 ? ? ? ? 48 8D 0D ? ? ? ? E8 ? ? ? ? 48 8D 0D ? ? ? ? 48 C7 05 ? ? ? ? ? ? ? ? [signature was not learned into a strict rule]
} // namespace DrawingRuntime

namespace DrawingMatrixRuntime {
    constexpr auto ProjMatrixRelative = 0x40;
} // namespace DrawingMatrixRuntime

namespace HudRuntime {
    constexpr auto Camera = 0x18;
    constexpr auto Input = 0x28;
    constexpr auto UserData = 0x60;
    constexpr auto SpellInfo = 0x68;
    constexpr auto CameraZoom = 0x324;
    constexpr auto CameraZoomLimits = 0x310;
    constexpr auto AltZoomLimits = 0x3D0;
    constexpr auto ZoomLockFlag1 = 0x344;
    constexpr auto ZoomLockFlag2 = 0x345;
    constexpr auto MouseWorldPos = 0x34;
    constexpr auto ViewportW2S = 0x2B0;
} // namespace HudRuntime

namespace HudZoomLayout {
    constexpr auto ZoomLimitsMin = 0x24;
    constexpr auto ZoomLimitsMax = 0x28;
} // namespace HudZoomLayout

namespace HudInputLayout {
    constexpr auto SelectedObjNetId = 0x60;
} // namespace HudInputLayout

namespace InputControllerLayout {
    constexpr auto ContextBase = 0x20;
    constexpr auto CurrentMode = 0x5F0;
    constexpr auto CurrentModeFromRoot = 0x610;
    constexpr auto GameplayMode = 0x1;
    constexpr auto KeyboardEntryMode = 0x8;
} // namespace InputControllerLayout

namespace ControlRuntime {
    constexpr auto IssueOrder = 0x2AAE10;   // 4C 89 4C 24 ? 4C 89 44 24 ? 88 54 24 ? 55 [signature was not learned into a strict rule]
    constexpr auto CastSpellWrap = 0xBC45D0;   // 40 53 48 83 EC ? 48 8B 05 ? ? ? ? 8B DA 0F B6 0D ? ? ? ? [signature was not learned into a strict rule]
    constexpr auto IsAlive = 0x2F2390;   // 40 53 48 83 EC ? 48 8B 01 48 8B D9 FF 90 ? ? ? ? 84 C0 74 ? 48 8D 8B ? ? ? ? 48 8B 01 [signature was not learned into a strict rule]
    constexpr auto GetSpellCastInfo = 0x28E9B0;   // 48 89 5C 24 ? 57 48 83 EC ? 4C 8B 81 ? ? ? ? 44 8B CA [signature was not learned into a strict rule]
    constexpr auto GetSpellSlot = 0x91E540;   // Offset ref: 0x91E540 (was 0x91E2D0). Sig: 48 89 5C 24 ? 55 56 57 41 56 41 57 48 8D AC 24 60 FD FF FF
    constexpr auto GetResourceType = 0x28BCF0;   // 0F B6 C2 48 69 C0 ? ? ? ? [signature was not learned into a strict rule]
    constexpr auto GetAttackDelay = 0x53CFD0;   // F3 0F 10 89 ? ? ? ? E9 ? ? ? ? [signature was not learned into a strict rule]
    constexpr auto GetAttackWindup = 0x53CED0;   // 48 89 5C 24 ?? 48 89 74 24 ?? 57 48 83 EC 60 48 8B 01 8B DA 0F 29 74 24 ?? [signature was not learned into a strict rule]
    constexpr auto GetBoundingRadius = 0x290250;   // 40 53 48 83 EC ? 48 83 B9 ? ? ? ? ? 48 8B D9 0F 29 74 24 ? [signature was not learned into a strict rule]
    constexpr auto IssueOrderFlag = 0x1D21D28;   // 89 05 ? ? ? ? E8 ? ? ? ? 8D 43 11 89 05 [signature was not learned into a strict rule]
    constexpr auto CastSpellFlag = 0x1D21CC0;   // C6 05 ? ? ? ? ? E8 ? ? ? ? 8B 50 ? 4C [signature was not learned into a strict rule]
    constexpr auto CastSpellSafe = 0xBC4800;   // 40 57 41 54 48 83 EC 58 4C 8B E2 E8 ? ? ? ? 48 8B F8 [signature was not learned into a strict rule]
    constexpr auto CanAttack = 0x200C40;   // 40 53 48 83 EC ? 48 83 79 48 00 48 8B D9 74 ? E8 ? ? ? ? 84 C0 74 ? 48 8B 4B 48 48 8B 53 50 48 8B 01 FF 50 18 8B 00 24 01 [signature was not learned into a strict rule]
} // namespace ControlRuntime

namespace BasicAttackRuntime {
    constexpr auto Base = 0x2C68;   // 48 8B 81 68 2C 00 00 C3 [rule:op1/consensus]
    constexpr auto Offset1 = 0x2C0;   // 5B C3 CC 48 8B 81 ? ? ? ? C3 [rule:insn2_op1/consensus]
    constexpr auto Offset2 = 0x70;   // 48 8B 41 ? 48 89 02 4C 89 42 08 F0 41 [rule:op1/index]
} // namespace BasicAttackRuntime

namespace EventRuntime {
    constexpr auto CreateClientEffect = 0x83C1F0;   // Offset ref: 0x83C1F0 (was 0x84B710)
    constexpr auto OnCreateObject = 0x52A980;   // 48 8B C4 4C 89 48 ? 55 48 8B EC [signature was not learned into a strict rule]
    constexpr auto OnGameUpdate = 0x524810;   // 48 89 5C 24 ? 55 56 57 41 54 41 55 48 83 EC ? 45 33 ED [signature was not learned into a strict rule]
    constexpr auto OnProcessSpell = 0x935D30;   // 40 55 53 41 55 41 56 41 57 48 8D AC 24 30 F0 FF FF [signature was not learned into a strict rule]
    constexpr auto OnSpellImpact = 0x92CB30;   // 40 53 48 83 EC ? 48 8B D9 0F 29 74 24 ? 48 83 C1 ? 0F 28 F2 [signature was not learned into a strict rule]
    constexpr auto OnStopCast = 0x936330;   // 48 89 6C 24 ? 57 48 83 EC ? 80 B9 ? ? ? ? ? 0F B6 EA [signature was not learned into a strict rule]
    constexpr auto OnFinishCast = 0x2D0950;   // 48 89 5C 24 ? 57 48 83 EC ? 48 8B F9 48 8B DA 8B 8A ? ? ? ? [signature was not learned into a strict rule]
    constexpr auto OnBuffAdd = 0xBDA550;   // 48 89 5C 24 ? 48 89 74 24 ? 57 48 83 EC ? 48 8B B1 ? ? ? ? 48 8B D9 [signature was not learned into a strict rule]
} // namespace EventRuntime

namespace EventPropertyRuntime {
    constexpr auto OnHeroActionStateChange = 0xEACDE0;   // 48 83 EC ? 44 8B 02 48 8D 81 ? ? ? ? 44 3B 00 74 ? 48 8B 49 ? 44 89 00 80 79 ? ? 74 ? 48 89 44 24 ? 48 8D 15 ? ? ? ? 33 C0 48 89 54 24 ? 4C 8D 44 24 ? 89 44 24 ? 89 44 24 ? 4C 8D 4C 24 ? 48 8B 01 33 D2 [signature was not learned into a strict rule]
    constexpr auto OnMinionFollowTargetNetIdChange = 0xEB5DB0;   // 44 8B 02 48 8D 41 74 44 3B 00 74 ? 48 8B 49 08 44 89 00 80 79 18 ? 74 ? 48 89 44 24 38 48 8D 15 ? ? ? ? 33 C0 48 89 54 24 30 4C 8D 44 24 60 89 44 24 40 89 44 24 60 4C 8D 4C 24 30 48 8B 01 BA ? ? ? ? 4C 89 44 24 20 41 B0 ? [signature was not learned into a strict rule]
} // namespace EventPropertyRuntime

namespace NavGridRuntime {
    constexpr auto NavGrid = 0x1DC2D10;   // 48 8B 05 ? ? ? ? 48 89 84 11 ? ? ? ? [signature was not learned into a strict rule]
    constexpr auto GetCollisionFlags = 0x11D05E0;   // 48 89 5C 24 ? 48 89 74 24 ? 48 89 7C 24 ? 41 56 48 83 EC ? 8B BC 24 ? ? ? ? [signature was not learned into a strict rule]
    constexpr auto GetAiManager = 0x2980A0;   // E8 ? ? ? ? 45 33 C9 48 8B D3 [signature was not learned into a strict rule]
    constexpr auto GetAiManagerInner = 0x299640;   // 48 2B C1 48 83 F8 ? 73 ? 90 0F B6 0C 02 F6 D1 30 0C 04 48 FF C0 48 83 F8 ? 72 ? 48 8B 04 24 48 8B 40 10 [signature was not learned into a strict rule]
} // namespace NavGridRuntime

namespace NavGridLayout {
    constexpr auto NavGridMgr = 0x8;
    constexpr auto MinX = 0xEC;
    constexpr auto MinZ = 0xF4;
    constexpr auto MaxX = 0xF8;
    constexpr auto MaxZ = 0x100;
    constexpr auto Data = 0x110;
    constexpr auto Width = 0x708;
    constexpr auto Height = 0x70C;
    constexpr auto Scale = 0x710;
    constexpr auto InverseScale = 0x714;
    constexpr auto GrassRegions = 0x158;
    constexpr auto CellSize = 0x10;
} // namespace NavGridLayout

namespace NavGridFlags {
    constexpr auto FlagWall = 0x1;
    constexpr auto FlagNoWalk = 0x2;
    constexpr auto FlagBrush = 0xC00;
    constexpr auto FlagSpecial = 0x1000;
} // namespace NavGridFlags

namespace SpellRuntime {
    constexpr auto SpellBookOffset = 0x30E8;   // 49 8D ? ? ? ? ? 8B D0 4C 8D ? ? E8 [rule:op1/consensus]
    constexpr auto ActiveSpellCast = 0x3120;
} // namespace SpellRuntime

namespace SpellBookLayout {
    constexpr auto SpellSlotArray = 0xAE0;   // 48 63 C2 48 8B 84 C1 [rule:insn1_op1/consensus]
} // namespace SpellBookLayout

namespace SpellSlotLayout {
    // Level — TWO offsets, both valid:
    constexpr auto SlotLevel = 0x1C;        // int — simple getter (IDA: sub_2993D0, read-only)
    constexpr auto SlotLevelAlt = 0x28;     // int — written during LevelUp (IDA: sub_36DB50, effective w/ modifiers)
    // Cooldown — TWO systems:
    constexpr auto SlotCooldown = 0x80;     // float — official CD getter (IDA: sub_858520, 0=off CD)
    constexpr auto SlotTotalCd = 0x88;      // float — full CD duration (IDA: sub_858590)
    constexpr auto SlotChargeTimer = 0x30;  // float — charge/ammo recharge timer
    constexpr auto SlotCooldownExpires = 0x70; // float — game time expiry (-1.0 = off CD)
    // Stacks / Cast state:
    constexpr auto SlotStacks = 0x5C;       // int (IDA: sub_85A010 stacks getter)
    constexpr auto SlotActiveSpellCast = 0x118; // ptr — active cast data, NULL=not casting (IDA: sub_9DA130)
    // Spell identity:
    constexpr auto SlotSpellInstanceVars = 0x108; // ptr to spell instance variables
    constexpr auto SlotSpellNameHash = 0x110;     // uint32 FNV hash of spell name
    constexpr auto SlotSpellInfo = 0x128;   // 48 8B 81 28 01 00 00 C3 [rule:op1/consensus]
    constexpr auto SlotSpellInput = 0x130;  // IDA: mov rax,[rcx+130h] @ sub_5D04D0 (= SpellDataResource ptr)
} // namespace SpellSlotLayout

namespace SpellDataResourceNameLayout {
    constexpr auto SpellNameStr = 0x28;     // std::string SSO within SpellDataResource
    constexpr auto SpellNameCap = 0x40;     // capacity (>0xF = heap ptr at SpellNameStr)
} // namespace SpellDataResourceNameLayout

namespace SpellInputLayout {
    constexpr auto InputTargetNetId = 0x14;
    constexpr auto InputStartPos = 0x18;
    constexpr auto InputEndPos = 0x24;
} // namespace SpellInputLayout

namespace SpellInfoLayout {
    constexpr auto InfoSpellData = 0x60;
    constexpr auto SpellInfoNamePtr = 0x28;
} // namespace SpellInfoLayout

namespace SpellDataLayout {
    constexpr auto DataSpellName = 0x80;
    constexpr auto DataManaCost = 0x5F4;
    constexpr auto DataResource = 0x8;
} // namespace SpellDataLayout

namespace SpellDataResourceLayout {
    constexpr auto DataResourceBase = 0x60;
    constexpr auto ResCastRange = 0x478;
    constexpr auto ResMissileSpeed = 0x518;
    constexpr auto ResLineWidth = 0x568;
    constexpr auto ResMaxAmmo = 0x3C0;
    constexpr auto ResCastType = 0x510;
    constexpr auto ResMissileSpec = 0x508;
    constexpr auto ResScriptName = 0x80;
    constexpr auto ResCooldownTime = 0x304;
    constexpr auto ResAmmoRecharge = 0x408;
    constexpr auto ResImgIconName = 0x2A0;
} // namespace SpellDataResourceLayout

namespace SpellCastInfoLayout {
    constexpr auto SpellData = 0x0;
    constexpr auto SrcIndex = 0x98;
    constexpr auto TargetIndex = 0x9C;  // IDA verified: MissileClient::TargetNetId(0x35C) - CastInfoBase(0x2C0) = 0x9C
    constexpr auto StartPos = 0xD8;
    constexpr auto EndPos = 0xE4;
    constexpr auto CastPos = 0xF0;
    constexpr auto TargetIndexWRONG = 0x108; // OLD — was container/array object, NOT target NetId
    constexpr auto CastDelay = 0x118;
    constexpr auto IsSpell = 0x134;
    constexpr auto IsSpecialAttack = 0x13E;
    constexpr auto IsAuto = 0x141;
    constexpr auto Slot = 0x14C;
} // namespace SpellCastInfoLayout

namespace BuffManagerRuntime {
    constexpr auto BuffManagerOffset = 0x2E40;   // 48 8D 8B 40 2E 00 00 48 8B D7 E8 ? ? ? ? 48 8B 03 [rule:op1/consensus]
} // namespace BuffManagerRuntime

namespace BuffManagerLayout {
    // Array 1: 16-byte entries {QWORD buff_ptr, QWORD refcounted_ptr} (IDA: sub_851D90)
    constexpr auto EntriesStart = 0x18;
    constexpr auto EntriesEnd = 0x20;
    constexpr auto EntriesCapacityEnd = 0x28;
    // Array 2: 8-byte BuffInstance* pointer entries (IDA: sub_BDA550 OnBuffAdd)
    constexpr auto Array2Start = 0x620;
    constexpr auto Array2End = 0x628;
} // namespace BuffManagerLayout

namespace BuffEntryLayout {
    constexpr auto EntryStride = 0x10;
    constexpr auto EntryBuff = 0x0;
    constexpr auto EntryAux = 0x8;
} // namespace BuffEntryLayout

namespace BuffDataLayout {
    constexpr auto BuffType = 0xC;
    constexpr auto BuffName = 0x8;         // SSO string directly on buff instance (was BuffNamePtr=0x10, WRONG)
    constexpr auto BuffScriptPtr = 0x10;   // ScriptBaseBuff* (used for hash comparison internally)
    constexpr auto BuffStartTime = 0x18;
    constexpr auto BuffEndTime = 0x1C;
    constexpr auto BuffStacks = 0x38;
    constexpr auto BuffStacksAlt = 0x3C;
    // SSO layout relative to BuffName (0x8):
    //   +0x00 (abs 0x08): inline char[16] or heap ptr
    //   +0x10 (abs 0x18): int length
    //   +0x18 (abs 0x20): int capacity (<=15 → inline, >15 → heap)
} // namespace BuffDataLayout

// BuffNameLayout removed — buff name is direct SSO at buff+0x8, no pointer indirection needed

namespace AiManagerRuntime {
    constexpr auto AiManagerOffset = 0x41E8;
} // namespace AiManagerRuntime

namespace AiManagerLayout {
    constexpr auto InnerManager = 0x10;
    constexpr auto TargetPosition = 0x34;
    constexpr auto Velocity = 0x318;
    constexpr auto IsMoving = 0x31C;
    constexpr auto CurrentSegment = 0x320;
    constexpr auto PathStart = 0x330;
    constexpr auto PathEndFallback = 0x33C;
    constexpr auto Segments = 0x348;
    constexpr auto SegmentsCount = 0x350;
    constexpr auto DashSpeed = 0x360;
    constexpr auto IsDashing = 0x384;
    constexpr auto ServerPos = 0x474;
    constexpr auto MoveVec3 = 0x480;
} // namespace AiManagerLayout

namespace AiManagerInnerCompatLayout {
    constexpr auto Offset = 0x41E8;
    constexpr auto InnerManager = 0x10;
    constexpr auto TargetPosition = 0x34;
    constexpr auto Velocity = 0x318;
    constexpr auto IsMoving = 0x31C;
    constexpr auto CurrentSegment = 0x320;
    constexpr auto PathStart = 0x330;
    constexpr auto PathEnd = 0x33C;
    constexpr auto Segments = 0x348;
    constexpr auto SegmentsCount = 0x350;
    constexpr auto HasPath = 0x354;
    constexpr auto DashSpeed = 0x360;
    constexpr auto DashMaxRangeSq = 0x374;
    constexpr auto DashDistRemaining = 0x378;
    constexpr auto DashDuration = 0x380;
    constexpr auto IsDashing = 0x384;
    constexpr auto DashEndPos = 0x3A8;
    constexpr auto ServerPos = 0x474;
    constexpr auto MoveVec3 = 0x480;
    constexpr auto DashTargetNetId = 0x48C;
    constexpr auto DashSecondaryNetId = 0x490;
    constexpr auto PreviousPos = 0x590;
} // namespace AiManagerInnerCompatLayout

namespace AiManagerObfuscationLayout {
    constexpr auto EncXorKey = 0x0;
    constexpr auto EncTableStart = 0x8;
    constexpr auto EncIsInit = 0x28;
    constexpr auto EncQwordCount = 0x29;
    constexpr auto EncByteCount = 0x2A;
    constexpr auto EncValueIndex = 0x2B;
} // namespace AiManagerObfuscationLayout

namespace AiManagerResolvedLayout {
    constexpr auto RawInnerPtr = 0x10;
    constexpr auto InnerTypePtr = 0x8;
    constexpr auto InnerTypeAdjust = 0x4;
    constexpr auto PathState = 0x300;
    constexpr auto PathEndFallback = 0x31C;
    constexpr auto Segments = 0x328;
    constexpr auto SegmentsCount = 0x330;
    constexpr auto ServerPosition = 0x454;
    constexpr auto MoveVector = 0x460;
    constexpr auto PreviousPosition = 0x570;
    constexpr auto NavModeFlag = 0x478;
    constexpr auto OrderPosition = 0x520;
    constexpr auto NavUnknownDword = 0x568;
    constexpr auto DashSpeedInner = 0x360;
    constexpr auto IsDashingInner = 0x384;
} // namespace AiManagerResolvedLayout

namespace AiManagerNavBaseLayout {
    constexpr auto RawInnerPtr = 0x10;
    constexpr auto InnerTypePtr = 0x8;
    constexpr auto InnerTypeAdjust = 0x4;
    constexpr auto PathState = 0x300;
    constexpr auto PathEndFallback = 0x31C;
    constexpr auto Segments = 0x328;
    constexpr auto SegmentsCount = 0x330;
    constexpr auto ServerPosition = 0x454;
    constexpr auto MoveVector = 0x460;
    constexpr auto PreviousPosition = 0x570;
    constexpr auto NavModeFlag = 0x478;
    constexpr auto OrderPosition = 0x520;
    constexpr auto NavUnknownDword = 0x568;
    constexpr auto DashSpeedInner = 0x360;
    constexpr auto IsDashingInner = 0x384;
} // namespace AiManagerNavBaseLayout

namespace AiManagerPathStateLayout {
    constexpr auto CurrentIndex = 0x0;
    constexpr auto FallbackEnd = 0x1C;
    constexpr auto PointsPtr = 0x28;
    constexpr auto Count = 0x30;
} // namespace AiManagerPathStateLayout

namespace MissileManagerTreeRuntime {
    constexpr auto MissileTree = 0x8;
} // namespace MissileManagerTreeRuntime

namespace MissileTreeHeaderLayout {
    constexpr auto Sentinel = 0x8;
} // namespace MissileTreeHeaderLayout

namespace MissileTreeNodeLayout {
    constexpr auto NodeLeft = 0x0;
    constexpr auto NodeParent = 0x8;
    constexpr auto NodeRight = 0x10;
    constexpr auto NodeIsNil = 0x19;
    constexpr auto NodeMissile = 0x28;
} // namespace MissileTreeNodeLayout

namespace ItemRuntime {
    constexpr auto ItemList = 0x4D20;
    constexpr auto SlotInfo = 0x10;
    constexpr auto InfoData = 0x38;
    constexpr auto InfoStacks = 0x64;
    constexpr auto DataItemId = 0xB4;
    constexpr auto DataAbilityHaste = 0x160;
    constexpr auto DataHealth = 0x164;
    constexpr auto DataArmor = 0x19C;
    constexpr auto DataMR = 0x1BC;
    constexpr auto DataAD = 0x1D8;
    constexpr auto DataAP = 0x1E0;
    constexpr auto DataAtkSpeedMult = 0x20C;
} // namespace ItemRuntime

namespace TypeFlagsRuntime {
    constexpr auto ObfuscatedField = 0x4C;
    constexpr auto IsObjectAI = 0x400;
    constexpr auto Minion = 0x800;
    constexpr auto Hero = 0x1000;
    constexpr auto Turret = 0x2000;
    constexpr auto Plant = 0x8000;
    constexpr auto LargeMonster = 0x80;
    constexpr auto BuffMonster = 0x100;
    constexpr auto AttackableObj = 0x8;
    constexpr auto VisibleObj = 0x10;
    constexpr auto RenderTarget = 0x20;
    constexpr auto IsRecalling = 0x4000;
} // namespace TypeFlagsRuntime

namespace TypeFlagAliasesRuntime {
    constexpr auto MinionSummon = 0x100;
} // namespace TypeFlagAliasesRuntime

namespace MinionRuntime {
    constexpr auto LaneArray = 0x68;
    constexpr auto LaneCount = 0x70;
    constexpr auto LaneType = 0x4CC9;
} // namespace MinionRuntime

namespace MinionClassRuntime {
    constexpr auto TypeOffset = 0x4C71;   // 0F B6 81 ? ? ? ? 3C ? 74 ? 2C ? 3C ? 76 (was 0x4C79, CE verified)
    constexpr auto Unset = 0x0;
    constexpr auto Pet = 0x1;
    constexpr auto JungleMonster = 0x2;
    constexpr auto TeamMinion = 0x3;
    constexpr auto MeleeLaneMinion = 0x4;
    constexpr auto RangedLaneMinion = 0x5;
    constexpr auto SiegeLaneMinion = 0x6;
    constexpr auto SuperLaneMinion = 0x7;
} // namespace MinionClassRuntime

namespace JungleTypeRuntime {
    constexpr auto TypeOffset = 0x4A84;
    constexpr auto Normal = 0x0;
    constexpr auto Baron = 0x1;
    constexpr auto Dragon = 0x2;
} // namespace JungleTypeRuntime

namespace ClassificationRuntime {
    constexpr auto CompareTypeFlags = 0x2A7D90;   // 40 56 48 83 EC ? 0F B6 41 ? [signature was not learned into a strict rule]
    constexpr auto IsJungleMonster = 0x2A71E0;   // 40 53 48 83 EC ? 48 8B 42 ? 48 8B D9 48 8B 51 ? [signature was not learned into a strict rule]
    constexpr auto GetJungleType = 0x677400;   // 40 53 56 41 56 48 83 EC 20 33 F6 4C 8B F1 89 74 [signature was not learned into a strict rule]
    constexpr auto IsClone = 0x2A60C0;   // 40 53 48 83 EC 20 48 8D 99 58 FD FF FF 48 8B 03 48 8B CB FF 90 ? ? ? ? 84 C0 74 ? 48 8B 03 48 8B CB FF 90 78 05 00 00 [signature was not learned into a strict rule]
    constexpr auto IsBuilding = 0x315790;   // 48 89 5C 24 ? 57 48 83 EC ? 48 8B F9 48 85 C9 74 ? [signature was not learned into a strict rule] | MCP_SIG: 48 89 5C 24 08 57 48 83 EC ? 48 8B F9 48 85 C9
    constexpr auto IsDead = 0x2A6327;   // E9 ? ? ? ? 48 81 E9 ? ? ? ? E9 ? ? ? ? CC CC CC CC CC CC CC CC 48 83 EC ? [signature was not learned into a strict rule]
    constexpr auto IsVulnerable = 0x2A7000;   // 40 55 48 83 EC ? 48 8B 01 [signature was not learned into a strict rule]
    constexpr auto IsDragon = 0x2A65F0;   // 40 53 48 83 EC ? 48 8D 99 ? ? ? ? 48 8B CB E8 ? ? ? ? 48 8D 15 ? ? ? ? [signature was not learned into a strict rule]
    constexpr auto IsElderDragon = 0x2A6660;   // E8 ? ? ? ? 0F B6 C8 83 FF ? [signature was not learned into a strict rule]
    constexpr auto IsBaron = 0x2A5A50;   // 40 53 48 83 EC ? 48 81 C1 ? ? ? ? E8 ? ? ? ? 48 8D 15 ? ? ? ? [signature was not learned into a strict rule]
    constexpr auto IsSelectable = 0x21A140;   // E8 ? ? ? ? 84 C0 0F 84 ? ? ? ? 45 85 E4 [signature was not learned into a strict rule]
    constexpr auto IsFleeing = 0x11509D0;   // 48 83 C4 ? 5F C3 B0 ? EB ? CC CC CC CC CC CC CC CC 48 8B 41 40 [signature was not learned into a strict rule]
    constexpr auto IsNoRender = 0x217390;   // E8 ? ? ? ? 84 C0 74 ? B0 ? 48 8B 5C 24 ? 48 83 C4 ? 5F C3 48 8B CB [signature was not learned into a strict rule]
    // unresolved: constexpr auto CanAttack = 0x1FC3F0;   // 40 53 48 83 EC ? 48 83 79 ? ? 48 8B D9 [signature was not learned into a strict rule]
} // namespace ClassificationRuntime

namespace UnitQueryRuntime {
    constexpr auto IsTargetableByUnit = 0x2A9470;   // 40 53 57 41 56 48 83 EC ? 48 8D B9 58 FD FF FF [signature was not learned into a strict rule]
    constexpr auto HasBuffOfType = 0x2A13E0;   // 48 81 C1 ? ? ? ? 48 8B 01 48 FF 60 ? CC CC 48 81 C1 ? ? ? ? 48 8B 01 [signature was not learned into a strict rule]
    constexpr auto GetGoldRedirectTgt = 0x207A90;   // E8 ? ? ? ? 48 85 C0 74 ? 48 8D 88 ? ? ? ? 48 8B D3 48 8B 01 [signature was not learned into a strict rule]
} // namespace UnitQueryRuntime

namespace EffectEmitterRuntime {
    constexpr auto Data = 0x8;
    constexpr auto Attachment = 0x38;
    constexpr auto TargetAttachment = 0x48;
} // namespace EffectEmitterRuntime

namespace EffectEmitterAttachmentLayout {
    constexpr auto Object = 0x0;
    constexpr auto Data = 0x8;
} // namespace EffectEmitterAttachmentLayout

namespace EffectEmitterDataLayout {
    constexpr auto OrientationRight = 0x118;
    constexpr auto OrientationUp = 0x128;
    constexpr auto OrientationForward = 0x138;
} // namespace EffectEmitterDataLayout

namespace CharacterDataLayout {
    constexpr auto CharacterDataPtr = 0x4028;   // CE: player+0x4028 → CharacterData struct
    constexpr auto CharacterHash = 0x10;         // CE: CharacterData+0x10 = SDBM hash (e.g. 0x84DCF93 = "Ezreal")
    constexpr auto BaseCharacterData = 0x28;     // Chimera reference
} // namespace CharacterDataLayout

namespace AnimationLayout {
    constexpr auto CharacterData = 0x40C8;
    constexpr auto Component = 0x4450;
    constexpr auto Queue = 0x4928;
    constexpr auto QueueEnd = 0x4930;
    constexpr auto QueueCapacityEnd = 0x4938;
    constexpr auto SkinIndex = 0x146;
    constexpr auto CharacterDataResource = 0x60;
    constexpr auto VariantEntries = 0x240;
    constexpr auto VariantEntryCount = 0x248;
    constexpr auto FallbackNamePtr = 0x250;
    constexpr auto FallbackState = 0x260;
    constexpr auto VariantEntryStride = 0xB0;
    constexpr auto VariantNamePtr = 0x8;
    constexpr auto VariantState = 0x18;
} // namespace AnimationLayout

namespace All {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x3C;
    constexpr auto Name = 0x68;   // Scanner: StdString "TESTBAN#0213" (was 0x58)
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Visibility = 0x2E0;
    constexpr auto Visible = 0x308;
    constexpr auto IsInvulnerable = 0x5A0;
    constexpr auto RecallState = 0xF48;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4328;   // IDA: lea rdx,[rcx+4328h] @ 0x29B0E7 (was 0x4330)
    constexpr auto Direction = 0x21D8;
    constexpr auto EffectEmitterHandle = 0x258;
    constexpr auto MissileClientHandle = 0x2D8;
    constexpr auto ItemList = 0x4D20;
} // namespace All

namespace AttackableUnit {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x3C;
    constexpr auto Name = 0x68;
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Visibility = 0x2E0;
    constexpr auto Visible = 0x308;
    constexpr auto IsInvulnerable = 0x5A0;
    constexpr auto RecallState = 0xF48;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4328;   // IDA: lea rdx,[rcx+4328h] @ 0x29B0E7 (was 0x4330)
    constexpr auto Direction = 0x21D8;
    constexpr auto HP = 0x1080;
    constexpr auto MaxHP = 0x10A8;
    constexpr auto HPMaxPenalty = 0x10D0;
    constexpr auto AllShield = 0x1120;
    constexpr auto PhysicalShield = 0x1148;
    constexpr auto MagicalShield = 0x1170;
    constexpr auto ChampSpecific = 0x1198;
    constexpr auto InHealAllied = 0x11C0;
    constexpr auto InHealEnemy = 0x11E8;
    constexpr auto InDamage = 0x1210;
    constexpr auto StopShieldFade = 0x1238;
    constexpr auto IsTargetable = 0xED0;
    constexpr auto TargetableFlags = 0xEF8;
    constexpr auto ActionState1 = 0x1470;
    constexpr auto ActionState2 = 0x14A8;
} // namespace AttackableUnit

namespace AIHeroClient {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x3C;
    constexpr auto Name = 0x68;
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Visibility = 0x2E0;
    constexpr auto Visible = 0x308;
    constexpr auto IsInvulnerable = 0x5A0;
    constexpr auto RecallState = 0xF48;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4328;   // IDA: lea rdx,[rcx+4328h] @ 0x29B0E7 (was 0x4330)
    constexpr auto Direction = 0x21D8;
    constexpr auto HP = 0x1080;
    constexpr auto MaxHP = 0x10A8;
    constexpr auto HPMaxPenalty = 0x10D0;
    constexpr auto AllShield = 0x1120;
    constexpr auto PhysicalShield = 0x1148;
    constexpr auto MagicalShield = 0x1170;
    constexpr auto ChampSpecific = 0x1198;
    constexpr auto InHealAllied = 0x11C0;
    constexpr auto InHealEnemy = 0x11E8;
    constexpr auto InDamage = 0x1210;
    constexpr auto StopShieldFade = 0x1238;
    constexpr auto IsTargetable = 0xED0;
    constexpr auto TargetableFlags = 0xEF8;
    constexpr auto ActionState1 = 0x1470;
    constexpr auto ActionState2 = 0x14A8;
    constexpr auto MP = 0x360;
    constexpr auto MaxMP = 0x388;
    constexpr auto PAR = 0xE00;
    constexpr auto MaxPAR = 0xE28;
    constexpr auto SAR = 0x108;
    constexpr auto MaxSAR = 0x130;
    constexpr auto PhysDmgPercent = 0xE78;
    constexpr auto MagicDmgPercent = 0xEA0;
    constexpr auto PercentCooldownMod = 0x1B88;
    constexpr auto AbilityHaste = 0x1BB0;
    constexpr auto PercentCooldownCapMod = 0x1BD8;
    constexpr auto PassiveCdEndTime = 0x1C00;
    constexpr auto PassiveCdTotalTime = 0x1C28;
    constexpr auto FlatPhysicalDmgMod = 0x1CC8;
    constexpr auto PercentPhysicalDmgMod = 0x1CF0;
    constexpr auto PercentBonusPhysDmgMod = 0x1D18;
    constexpr auto PercentBasePhysDmgFlat = 0x1D40;
    constexpr auto FlatMagicDmgMod = 0x1D68;
    constexpr auto PercentMagicDmgMod = 0x1D90;
    constexpr auto FlatMagicReduction = 0x1DB8;
    constexpr auto PercentMagicReduction = 0x1DE0;
    constexpr auto FlatCastRangeMod = 0x1E08;
    constexpr auto AttackSpeedMod = 0x1E30;
    constexpr auto PercentAttackSpeedMod = 0x1E58;
    constexpr auto PercentMultiAtkSpeedMod = 0x1E80;
    constexpr auto PercentHealingAmountMod = 0x1EA8;
    constexpr auto BaseAttackDamage = 0x1ED0;
    constexpr auto BaseAtkDmgSansScale = 0x1EF8;
    constexpr auto FlatBaseAtkDmgMod = 0x1F20;
    constexpr auto PercentBaseAtkDmgMod = 0x1F48;
    constexpr auto BaseAbilityDamage = 0x1F70;
    constexpr auto CritDamageMultiplier = 0x1F98;
    constexpr auto ScaleSkinCoef = 0x1FC0;
    constexpr auto Dodge = 0x1FE8;
    constexpr auto Crit = 0x2010;
    constexpr auto Armor = 0x2060;
    constexpr auto BonusArmor = 0x2088;
    constexpr auto SpellBlock = 0x20B0;
    constexpr auto BonusSpellBlock = 0x20D8;
    constexpr auto HPRegenRate = 0x2100;
    constexpr auto BaseHPRegenRate = 0x2128;
    constexpr auto MoveSpeed = 0x2150;
    constexpr auto MoveSpeedBaseIncrease = 0x2178;
    constexpr auto AttackRange = 0x21A0;
    constexpr auto FlatBubbleRadiusMod = 0x21C8;
    constexpr auto PercentBubbleRadiusMod = 0x21F0;
    constexpr auto FlatArmorPen = 0x2218;
    constexpr auto PhysicalLethality = 0x2240;
    constexpr auto PercentArmorPen = 0x2268;
    constexpr auto PercentBonusArmorPen = 0x2290;
    constexpr auto PercentCritBonusArmorPen = 0x22B8;
    constexpr auto PercentCritTotalArmorPen = 0x22E0;
    constexpr auto FlatMagicPen = 0x2308;
    constexpr auto MagicLethality = 0x2330;
    constexpr auto PercentMagicPen = 0x2358;
    constexpr auto PercentBonusMagicPen = 0x2380;
    constexpr auto PercentLifeSteal = 0x23A8;
    constexpr auto PercentSpellVamp = 0x23D0;
    constexpr auto PercentOmnivamp = 0x23F8;
    constexpr auto PercentPhysicalVamp = 0x2420;
    constexpr auto PathfindingRadiusMod = 0x2448;
    constexpr auto PercentCCReduction = 0x2470;
    constexpr auto PercentEXPBonus = 0x2498;
    constexpr auto FlatBaseArmorMod = 0x24C0;
    constexpr auto FlatBaseSpellBlockMod = 0x24E8;
    constexpr auto PARRegenRate = 0x2510;
    constexpr auto PrimaryARBaseRegenRate = 0x2538;
    constexpr auto SecondaryARRegenRate = 0x2560;
    constexpr auto SecondaryARBaseRegenRate = 0x2588;
    constexpr auto FlatBaseAttackSpeedMod = 0x25B0;
    constexpr auto Gold = 0x2830;
    constexpr auto GoldTotal = 0x2858;
    constexpr auto MinimumGold = 0x2880;
    constexpr auto CombatType = 0x2C98;
    constexpr auto FollowerTargetDelay = 0x2DB8;
    constexpr auto Exp = 0x4CF0;
    constexpr auto LevelRef = 0x4D18;
    constexpr auto LevelUpPoints = 0x4D78;
    constexpr auto VisionScore = 0x55E0;
    constexpr auto ShutdownValue = 0x5608;
    constexpr auto BaseGoldOnDeath = 0x5630;
    constexpr auto NeutralMinionsKilled = 0x5658;
    constexpr auto EffectEmitterHandle = 0x258;
    constexpr auto MissileClientHandle = 0x2D8;
    constexpr auto ItemList = 0x4D20;
    constexpr auto SpellBookOffset = 0x30E8;
    constexpr auto ActiveSpellCast = 0x3120;
    constexpr auto BuffManagerOffset = 0x2E40;
    constexpr auto AiManagerOffset = 0x41E8;
} // namespace AIHeroClient

namespace AIMinionClient {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x3C;
    constexpr auto Name = 0x68;
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Visibility = 0x2E0;
    constexpr auto Visible = 0x308;
    constexpr auto IsInvulnerable = 0x5A0;
    constexpr auto RecallState = 0xF48;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4328;   // IDA: lea rdx,[rcx+4328h] @ 0x29B0E7 (was 0x4330)
    constexpr auto Direction = 0x21D8;
    constexpr auto HP = 0x1080;
    constexpr auto MaxHP = 0x10A8;
    constexpr auto HPMaxPenalty = 0x10D0;
    constexpr auto AllShield = 0x1120;
    constexpr auto PhysicalShield = 0x1148;
    constexpr auto MagicalShield = 0x1170;
    constexpr auto ChampSpecific = 0x1198;
    constexpr auto InHealAllied = 0x11C0;
    constexpr auto InHealEnemy = 0x11E8;
    constexpr auto InDamage = 0x1210;
    constexpr auto StopShieldFade = 0x1238;
    constexpr auto IsTargetable = 0xED0;
    constexpr auto TargetableFlags = 0xEF8;
    constexpr auto ActionState1 = 0x1470;
    constexpr auto ActionState2 = 0x14A8;
    constexpr auto MP = 0x360;
    constexpr auto MaxMP = 0x388;
    constexpr auto PAR = 0xE00;
    constexpr auto MaxPAR = 0xE28;
    constexpr auto SAR = 0x108;
    constexpr auto MaxSAR = 0x130;
    constexpr auto PhysDmgPercent = 0xE78;
    constexpr auto MagicDmgPercent = 0xEA0;
    constexpr auto PercentCooldownMod = 0x1B88;
    constexpr auto AbilityHaste = 0x1BB0;
    constexpr auto PercentCooldownCapMod = 0x1BD8;
    constexpr auto PassiveCdEndTime = 0x1C00;
    constexpr auto PassiveCdTotalTime = 0x1C28;
    constexpr auto FlatPhysicalDmgMod = 0x1CC8;
    constexpr auto PercentPhysicalDmgMod = 0x1CF0;
    constexpr auto PercentBonusPhysDmgMod = 0x1D18;
    constexpr auto PercentBasePhysDmgFlat = 0x1D40;
    constexpr auto FlatMagicDmgMod = 0x1D68;
    constexpr auto PercentMagicDmgMod = 0x1D90;
    constexpr auto FlatMagicReduction = 0x1DB8;
    constexpr auto PercentMagicReduction = 0x1DE0;
    constexpr auto FlatCastRangeMod = 0x1E08;
    constexpr auto AttackSpeedMod = 0x1E30;
    constexpr auto PercentAttackSpeedMod = 0x1E58;
    constexpr auto PercentMultiAtkSpeedMod = 0x1E80;
    constexpr auto PercentHealingAmountMod = 0x1EA8;
    constexpr auto BaseAttackDamage = 0x1ED0;
    constexpr auto BaseAtkDmgSansScale = 0x1EF8;
    constexpr auto FlatBaseAtkDmgMod = 0x1F20;
    constexpr auto PercentBaseAtkDmgMod = 0x1F48;
    constexpr auto BaseAbilityDamage = 0x1F70;
    constexpr auto CritDamageMultiplier = 0x1F98;
    constexpr auto ScaleSkinCoef = 0x1FC0;
    constexpr auto Dodge = 0x1FE8;
    constexpr auto Crit = 0x2010;
    constexpr auto Armor = 0x2060;
    constexpr auto BonusArmor = 0x2088;
    constexpr auto SpellBlock = 0x20B0;
    constexpr auto BonusSpellBlock = 0x20D8;
    constexpr auto HPRegenRate = 0x2100;
    constexpr auto BaseHPRegenRate = 0x2128;
    constexpr auto MoveSpeed = 0x2150;
    constexpr auto MoveSpeedBaseIncrease = 0x2178;
    constexpr auto AttackRange = 0x21A0;
    constexpr auto FlatBubbleRadiusMod = 0x21C8;
    constexpr auto PercentBubbleRadiusMod = 0x21F0;
    constexpr auto FlatArmorPen = 0x2218;
    constexpr auto PhysicalLethality = 0x2240;
    constexpr auto PercentArmorPen = 0x2268;
    constexpr auto PercentBonusArmorPen = 0x2290;
    constexpr auto PercentCritBonusArmorPen = 0x22B8;
    constexpr auto PercentCritTotalArmorPen = 0x22E0;
    constexpr auto FlatMagicPen = 0x2308;
    constexpr auto MagicLethality = 0x2330;
    constexpr auto PercentMagicPen = 0x2358;
    constexpr auto PercentBonusMagicPen = 0x2380;
    constexpr auto PercentLifeSteal = 0x23A8;
    constexpr auto PercentSpellVamp = 0x23D0;
    constexpr auto PercentOmnivamp = 0x23F8;
    constexpr auto PercentPhysicalVamp = 0x2420;
    constexpr auto PathfindingRadiusMod = 0x2448;
    constexpr auto PercentCCReduction = 0x2470;
    constexpr auto PercentEXPBonus = 0x2498;
    constexpr auto FlatBaseArmorMod = 0x24C0;
    constexpr auto FlatBaseSpellBlockMod = 0x24E8;
    constexpr auto PARRegenRate = 0x2510;
    constexpr auto PrimaryARBaseRegenRate = 0x2538;
    constexpr auto SecondaryARRegenRate = 0x2560;
    constexpr auto SecondaryARBaseRegenRate = 0x2588;
    constexpr auto FlatBaseAttackSpeedMod = 0x25B0;
    constexpr auto SpellBookOffset = 0x30E8;
    constexpr auto ActiveSpellCast = 0x3120;
    constexpr auto BuffManagerOffset = 0x2E40;
    constexpr auto AiManagerOffset = 0x41E8;
    constexpr auto LaneArray = 0x68;
    constexpr auto LaneCount = 0x70;
    constexpr auto LaneType = 0x4CC9;
    constexpr auto JungleTypeOffset = 0x4A84;
    constexpr auto TypeFlagsField = 0x4C;
} // namespace AIMinionClient

namespace MissileClient {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x3C;
    constexpr auto Name = 0x68;
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4328;   // IDA: lea rdx,[rcx+4328h] @ 0x29B0E7 (was 0x4330)
    constexpr auto Direction = 0x21D8;
    constexpr auto SpellDataPtr = 0x128;
    constexpr auto CastInfoBase = 0x2C0;
    constexpr auto SpellName = 0x2E0;
    constexpr auto MissileName = 0x308;
    constexpr auto CasterNetId = 0x358;
    constexpr auto TargetNetId = 0x35C;
    constexpr auto MissileNetId = 0x364;
    constexpr auto StartPos = 0x330;
    constexpr auto EndPos = 0x33C;
    constexpr auto CastEndPos = 0x34C;
} // namespace MissileClient

namespace Static {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x3C;
    constexpr auto Name = 0x68;
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Visibility = 0x2E0;
    constexpr auto Visible = 0x308;
    constexpr auto IsInvulnerable = 0x5A0;
    constexpr auto RecallState = 0xF48;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4328;   // IDA: lea rdx,[rcx+4328h] @ 0x29B0E7 (was 0x4330)
    constexpr auto Direction = 0x21D8;
    constexpr auto EffectEmitterHandle = 0x258;
    constexpr auto MissileClientHandle = 0x2D8;
    constexpr auto ItemList = 0x4D20;
} // namespace Static

namespace AITurretClient {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x3C;
    constexpr auto Name = 0x68;
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Visibility = 0x2E0;
    constexpr auto Visible = 0x308;
    constexpr auto IsInvulnerable = 0x5A0;
    constexpr auto RecallState = 0xF48;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4328;   // IDA: lea rdx,[rcx+4328h] @ 0x29B0E7 (was 0x4330)
    constexpr auto Direction = 0x21D8;
    constexpr auto HP = 0x1080;
    constexpr auto MaxHP = 0x10A8;
    constexpr auto HPMaxPenalty = 0x10D0;
    constexpr auto AllShield = 0x1120;
    constexpr auto PhysicalShield = 0x1148;
    constexpr auto MagicalShield = 0x1170;
    constexpr auto ChampSpecific = 0x1198;
    constexpr auto InHealAllied = 0x11C0;
    constexpr auto InHealEnemy = 0x11E8;
    constexpr auto InDamage = 0x1210;
    constexpr auto StopShieldFade = 0x1238;
    constexpr auto IsTargetable = 0xED0;
    constexpr auto TargetableFlags = 0xEF8;
    constexpr auto ActionState1 = 0x1470;
    constexpr auto ActionState2 = 0x14A8;
    constexpr auto PhysDmgPercent = 0xE78;
    constexpr auto MagicDmgPercent = 0xEA0;
    constexpr auto SpellBookOffset = 0x30E8;
    constexpr auto ActiveSpellCast = 0x3120;
    constexpr auto BuffManagerOffset = 0x2E40;
    constexpr auto AiManagerOffset = 0x41E8;
} // namespace AITurretClient

namespace EffectEmitter {
    constexpr auto Data = 0x8;
    constexpr auto Attachment = 0x38;
    constexpr auto TargetAttachment = 0x48;
} // namespace EffectEmitter

namespace BarracksDampenerClient {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x3C;
    constexpr auto Name = 0x68;
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Visibility = 0x2E0;
    constexpr auto Visible = 0x308;
    constexpr auto IsInvulnerable = 0x5A0;
    constexpr auto RecallState = 0xF48;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4328;   // IDA: lea rdx,[rcx+4328h] @ 0x29B0E7 (was 0x4330)
    constexpr auto Direction = 0x21D8;
    constexpr auto HP = 0x1080;
    constexpr auto MaxHP = 0x10A8;
    constexpr auto HPMaxPenalty = 0x10D0;
    constexpr auto AllShield = 0x1120;
    constexpr auto PhysicalShield = 0x1148;
    constexpr auto MagicalShield = 0x1170;
    constexpr auto ChampSpecific = 0x1198;
    constexpr auto InHealAllied = 0x11C0;
    constexpr auto InHealEnemy = 0x11E8;
    constexpr auto InDamage = 0x1210;
    constexpr auto StopShieldFade = 0x1238;
    constexpr auto IsTargetable = 0xED0;
    constexpr auto TargetableFlags = 0xEF8;
    constexpr auto ActionState1 = 0x1470;
    constexpr auto ActionState2 = 0x14A8;
} // namespace BarracksDampenerClient

namespace HQClient {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x3C;
    constexpr auto Name = 0x68;
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Visibility = 0x2E0;
    constexpr auto Visible = 0x308;
    constexpr auto IsInvulnerable = 0x5A0;
    constexpr auto RecallState = 0xF48;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4328;   // IDA: lea rdx,[rcx+4328h] @ 0x29B0E7 (was 0x4330)
    constexpr auto Direction = 0x21D8;
    constexpr auto HP = 0x1080;
    constexpr auto MaxHP = 0x10A8;
    constexpr auto HPMaxPenalty = 0x10D0;
    constexpr auto AllShield = 0x1120;
    constexpr auto PhysicalShield = 0x1148;
    constexpr auto MagicalShield = 0x1170;
    constexpr auto ChampSpecific = 0x1198;
    constexpr auto InHealAllied = 0x11C0;
    constexpr auto InHealEnemy = 0x11E8;
    constexpr auto InDamage = 0x1210;
    constexpr auto StopShieldFade = 0x1238;
    constexpr auto IsTargetable = 0xED0;
    constexpr auto TargetableFlags = 0xEF8;
    constexpr auto ActionState1 = 0x1470;
    constexpr auto ActionState2 = 0x14A8;
} // namespace HQClient

namespace ShopClient {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x3C;
    constexpr auto Name = 0x68;
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Visibility = 0x2E0;
    constexpr auto Visible = 0x308;
    constexpr auto IsInvulnerable = 0x5A0;
    constexpr auto RecallState = 0xF48;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4328;   // IDA: lea rdx,[rcx+4328h] @ 0x29B0E7 (was 0x4330)
    constexpr auto Direction = 0x21D8;
} // namespace ShopClient

namespace Obj_SpawnPoint {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x3C;
    constexpr auto Name = 0x68;
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Visibility = 0x2E0;
    constexpr auto Visible = 0x308;
    constexpr auto IsInvulnerable = 0x5A0;
    constexpr auto RecallState = 0xF48;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4328;   // IDA: lea rdx,[rcx+4328h] @ 0x29B0E7 (was 0x4330)
    constexpr auto Direction = 0x21D8;
} // namespace Obj_SpawnPoint

// ============================================================================
// New namespaces from Offset reference (freshly reversed)
// ============================================================================

namespace GadgetRuntime {
    // ROP gadgets for return address spoofing
    // JMP [rbx] (FF 23): 0x4AAA3, 0x5915A, 0x59861, 0x6ADB8, 0xEC0B0
    // JMP rcx; RET (FF E1 C3):
    constexpr auto ThreadTrampoline = 0x18D1A7C;
} // namespace GadgetRuntime

namespace DirectInputRuntime {
    // Keyboard (IDirectInputDevice8*)
    constexpr auto KeyboardDevice = 0x1E68BF8;
    constexpr auto KeyboardBuffer = 0x1E68C08;
    constexpr auto KeyboardCount  = 0x1E68C28;
    constexpr auto KeyboardFlag   = 0x1E68C48;
    // Mouse (IDirectInputDevice8*)
    constexpr auto MouseDevice    = 0x1E68C00;
    constexpr auto MouseBuffer    = 0x1E68C10;
    constexpr auto MouseCount     = 0x1E68C38;
    // vtable offsets (COM, stable across builds)
    constexpr auto VT_GetDeviceState = 0x48;
    constexpr auto VT_GetDeviceData  = 0x50;
} // namespace DirectInputRuntime

namespace ZoomRuntime {
    // Camera chain: HudInstance → +0x18 → CameraStruct
    constexpr auto HudToCameraPtr    = 0x18;
    constexpr auto CurrentZoom       = 0x324;
    constexpr auto ZoomConfigPtr     = 0x3D0;
    constexpr auto ZoomFallbackPtr   = 0x310;
    constexpr auto DisableZoomClamp  = 0x345;
    constexpr auto ZoomClampFlag     = 0x344;
    // ZoomConfig / ZoomFallbackConfig layout:
    constexpr auto ZC_MinZoom        = 0x24;
    constexpr auto ZC_MaxZoom        = 0x28;
    // Read-only .rdata constants (integrity checked):
    constexpr auto HardcodedMaxZoom  = 0x1916924;
    constexpr auto ZoomEnableConfig  = 0x1E31E80;
} // namespace ZoomRuntime

namespace SkinRuntime {
    // ModSkin: CharacterDataStack at obj+0x2C68
    constexpr auto SkinNetID         = 0x1440;
    constexpr auto SkinName          = 0x1448;  // std::string (skin/champion name)
    constexpr auto ModelName         = 0x1468;  // std::string (model name)
    constexpr auto SkinChangeFlag    = 0x1488;  // byte bool
    constexpr auto SkinParam1        = 0x148C;  // dword
    constexpr auto SkinParam2        = 0x1490;  // dword
} // namespace SkinRuntime

namespace ShopRuntime {
    constexpr auto IsShopOpen        = 0x1DBBF98; // GLOBAL dword
} // namespace ShopRuntime

namespace EventSpellCastInfoLayout {
    // SpellCastInfo fields from event handlers (OnProcessSpell/OnStopCast)
    constexpr auto SCI_CasterNetId   = 0x00A0;
    constexpr auto SCI_SpellSlotShort = 0x0146; // int16
    constexpr auto SCI_SpellSlotInt  = 0x0154;  // int
    constexpr auto SCI_IsStopCast    = 0x01AC;  // byte bool
    constexpr auto SCI_CastState     = 0x0198;  // byte bool
    constexpr auto SCI_CastData      = 0x01E8;  // ptr
} // namespace EventSpellCastInfoLayout

namespace NavGridCellLayout {
    // Cell structure (16 bytes each at CellArray + 16 * (x + z * Width)):
    //   +0x00: QWORD ptr → overlay data (null = use inline flags)
    //   +0x08: WORD flags (if overlay null; if overlay, use *overlay+6)
    constexpr auto CellOverlay       = 0x00;
    constexpr auto CellFlags         = 0x08;
    constexpr auto OverlayFlagsOff   = 0x06;  // *(overlay + 6) for overlaid cells
    constexpr auto CellStride        = 16;
    // Cell flag bits (from Offset reference — verified by IDA sub_11D0C30):
    constexpr auto CELL_WALL         = 0x0002;
    constexpr auto CELL_BRUSH        = 0x0004;
    constexpr auto CELL_WATER        = 0x0010;
    constexpr auto CELL_BUILDING     = 0x0040;
    constexpr auto CELL_VISION       = 0x0080;
    constexpr auto CELL_PASSABILITY  = 0x0C00;
    constexpr auto HalfCellSize      = 0x0718; // float (NavGridData + 0x718)
} // namespace NavGridCellLayout

namespace CombatStatsLayout {
    // Stat/modifier block offsets (from Offset reference combat namespace)
    constexpr auto BaseAttackDamage                 = 0x0348;
    constexpr auto AttackSpeedMod                   = 0x02A8;
    constexpr auto PercentAttackSpeedMod            = 0x02D0;
    constexpr auto PercentMultiplicativeAtkSpeedMod = 0x02F8;
    constexpr auto AttackRange                      = 0x0618;
    constexpr auto Crit                             = 0x0488;
    constexpr auto CritDamageMultiplier             = 0x0410;
    constexpr auto Armor                            = 0x04D8;
    constexpr auto SpellBlock                       = 0x0528;
    constexpr auto BonusArmor                       = 0x0500;
    constexpr auto BonusSpellBlock                  = 0x0550;
    constexpr auto Dodge                            = 0x0460;
    constexpr auto FlatPhysicalDamageMod            = 0x0140;
    constexpr auto PercentPhysicalDamageMod         = 0x0168;
    constexpr auto FlatMagicDamageMod               = 0x01E0;
    constexpr auto PercentMagicDamageMod            = 0x0208;
    constexpr auto HPRegenRate                      = 0x0578;
    constexpr auto PrimaryARRegenRateRep            = 0x0988;
    constexpr auto FlatBaseArmorMod                 = 0x0938;
    constexpr auto FlatBaseSpellBlockMod            = 0x0960;
} // namespace CombatStatsLayout

namespace HeroFieldsLayout {
    constexpr auto Gold                      = 0x2830;
    constexpr auto GoldTotal                 = 0x2858;
    constexpr auto MinimumGold               = 0x2880;
    constexpr auto SkillUpLevelDeltaRep      = 0x4D38;
    constexpr auto EvolvePoints              = 0x4BF8;
    constexpr auto Flags                     = 0x4C20;
    constexpr auto Exp                       = 0x4CE8;
    constexpr auto LevelRef                  = 0x4D10;
    constexpr auto VisionScore               = 0x55D8;
    constexpr auto ShutdownValue             = 0x5600;
    constexpr auto BaseGoldGivenOnDeath      = 0x5628;
    constexpr auto NumNeutralMinionsKilled   = 0x5650;
    constexpr auto InputLocks                = 0x56C8;
    constexpr auto AutoBuildItemId           = 0x5820;
    constexpr auto CombatType                = 0x2C98;
    constexpr auto LargePipBitField          = 0x04E0;
    constexpr auto MediumPipBitField         = 0x0508;
} // namespace HeroFieldsLayout

namespace MinionFieldsLayout {
    constexpr auto FollowTargetNetId         = 0x2D90;
    constexpr auto FollowerTargetDelay       = 0x2DB8;
    constexpr auto PercentDmgToBarracksMod   = 0x1C50;
    constexpr auto FlatDmgReductionBarracks  = 0x1C78;
    constexpr auto IncreasedMoveSpeedMod     = 0x1CA0;
} // namespace MinionFieldsLayout

namespace TurretFieldsLayout {
    constexpr auto PropertyManager           = 0x2C88;
    constexpr auto PalisadesCount            = 0x4AF0;
    constexpr auto MaxPalisadesCount         = 0x4B18;
} // namespace TurretFieldsLayout

namespace AIBaseFieldsLayout {
    constexpr auto Lifetime                  = 0x0DB0;
    constexpr auto MaxLifetime               = 0x0DD8;
    constexpr auto LifetimeTicks             = 0x0E00;
    constexpr auto IsTargetable              = 0x0ED0;
    constexpr auto IsTargetableToTeam        = 0x0EF8;
    constexpr auto PhysDmgPctMod             = 0x0E78;
    constexpr auto MagicDmgPctMod            = 0x0EA0;
    constexpr auto MoveSpeed                 = 0x05C8;
    constexpr auto MoveSpeedBaseIncrease     = 0x05F0;
    constexpr auto ScaleSkinCoef             = 0x0438;
    constexpr auto FlatBubbleRadiusMod       = 0x0640;
    constexpr auto PercentBubbleRadiusMod    = 0x0668;
    constexpr auto PathfindingRadiusMod      = 0x08C0;
} // namespace AIBaseFieldsLayout

namespace ObjectFieldsLayout {
    // Core object fields (Offset ref obj namespace)
    constexpr auto Index             = 0x0020;  // uint32 (NetworkID/ObjIndex)
    constexpr auto Name              = 0x0068;  // std::string SSO
    constexpr auto NameCapacity      = 0x0080;  // if >0xF → heap ptr at Name
    constexpr auto SelectionHeight   = 0x0088;  // float
    constexpr auto SelectionRadius   = 0x008C;  // float
    constexpr auto Visible           = 0x0308;  // bool (fog of war)
    constexpr auto IsCloneFlag       = 0x0218;
    constexpr auto IsDeadFlag        = 0x0250;
    constexpr auto Team              = 0x0259;  // uint8 (encrypted, lookup via table)
    constexpr auto Position          = 0x025C;  // Vector3 (encrypted)
    constexpr auto CharIntermediate  = 0x02A8;  // ptr
    constexpr auto DataStackBase     = 0x02C0;  // ptr
    constexpr auto CharDataBase      = 0x2C68;  // ptr
    constexpr auto AiManagerPtr      = 0x41E8;  // ENCRYPTED ptr (XOR)
    constexpr auto CharName          = 0x4328;  // std::string (champion/skin name)
    constexpr auto CharNameCapacity  = 0x4340;  // if >0xF → heap ptr
} // namespace ObjectFieldsLayout

namespace SpellDataParamLayout {
    // SpellData parameter indices (from Offset ref sub_333E00)
    constexpr auto PARAM_TARGETTINGTYPE       = 0x10;
    constexpr auto PARAM_COOLDOWN             = 0x15;
    constexpr auto PARAM_CASTRANGE            = 0x18;
    constexpr auto PARAM_LINEWIDTH            = 0x22;
    constexpr auto PARAM_MISSILESPEED         = 0x27;
    constexpr auto PARAM_MAXAMMOCOUNT         = 0x28;
    constexpr auto PARAM_CHARGEUPDATEINTERVAL = 0x2A;
} // namespace SpellDataParamLayout

namespace MissileSpellCastInfoLayout {
    // SpellCastInfo on missile/caster (obj+0x4010..0x4018, entry=0x190)
    constexpr auto CastInfoStart     = 0x4010;
    constexpr auto CastInfoEnd       = 0x4018;
    constexpr auto CastInfoEntrySize = 0x190;
    constexpr auto CI_SpellSlotIdx   = 0x08;
    constexpr auto CI_StartPos       = 0x80;
    constexpr auto CI_EndPos         = 0x8C;
    constexpr auto CI_TargetPos      = 0x98;
    constexpr auto CI_CasterNetId    = 0xC0;
    constexpr auto CI_TargetNetId    = 0x100;
    constexpr auto CI_MissileNetId   = 0x108;
} // namespace MissileSpellCastInfoLayout

namespace AiManagerNavDataLayout {
    // NavData offsets from Offset reference (flat on resolved inner struct)
    constexpr auto MoveSpeed         = 0x02F8;
    constexpr auto NavFlag           = 0x02FD;
    constexpr auto ServerPosX        = 0x0310;
    constexpr auto ServerPosZ        = 0x0318;
    constexpr auto ServerPos         = 0x031C;
    constexpr auto SegmentsPtr       = 0x0328;
    constexpr auto SegmentsCount     = 0x0330;
    constexpr auto CurrentSegment    = 0x0334;
    constexpr auto DashSpeedCalc     = 0x0340;
    constexpr auto DashMaxRangeSq    = 0x0354;
    constexpr auto DashDistRemain    = 0x0358;
    constexpr auto IsDashingInner    = 0x035C;
    constexpr auto DashDuration      = 0x0360;
    constexpr auto PathStart         = 0x0388;
    constexpr auto PathEndFallback   = 0x03A0;
    constexpr auto ArrivedFlag       = 0x0450;
    constexpr auto CurrentPosX       = 0x0454;
    constexpr auto CurrentPosY       = 0x0458;
    constexpr auto CurrentPosZ       = 0x045C;
    constexpr auto DashTargetNetId   = 0x046C;
    constexpr auto DashSecondaryId   = 0x0470;
    constexpr auto MoveOverrideFlag  = 0x0474;
    constexpr auto PreviousPosX      = 0x0570;
    constexpr auto PreviousPosY      = 0x0574;
    constexpr auto PreviousPosZ      = 0x0578;
    constexpr auto VelocityX         = 0x0588;
    constexpr auto VelocityY         = 0x058C;
    constexpr auto VelocityZ         = 0x0590;
} // namespace AiManagerNavDataLayout

namespace TargetRuntime {
    constexpr auto AITargetComponent = 0x1498;
} // namespace TargetRuntime

}