#pragma once

// Generated by tools/ida_nightsharp_offset_dump_plugin.py
// Cleaned: removed per-class duplicates and orphaned namespaces
// Only namespaces referenced by Offset1.h are kept.

namespace Offset {

namespace GameObjectsRuntime {
    constexpr auto Player = 0x1E0F9A0;
    constexpr auto Objects = 0x1DD7168;
    constexpr auto Heroes = 0x1DD71C0;
    constexpr auto Minions = 0x1DD71B8;
    constexpr auto Missiles = 0x1DD7318;
    constexpr auto Turrets = 0x1DDB258;
    constexpr auto UnderMouseObject = 0x1DDB290;
} // namespace GameObjectsRuntime

namespace ObjectManagerRuntime {
    constexpr auto ManagerListItems = 0x8;
    constexpr auto ManagerListSize = 0x10;
    constexpr auto GetFirstObject = 0x9ED080;
    constexpr auto GetNextObject = 0x50E230;
    constexpr auto FindObject = 0x5348B0;
} // namespace ObjectManagerRuntime

namespace GameRuntime {
    constexpr auto GameTime = 0x1DE5420;
    constexpr auto NetInstance = 0x1DD7160;
    constexpr auto ChatClient = 0x1DEAED8;
    constexpr auto ChatInstance = 0x1DDB2A0;
    constexpr auto ShopInstance = 0x1DEAEF0;
    constexpr auto OpenWindowsArray = 0x1E7F158;
    constexpr auto OpenWindowsCount = 0x1E7F160;
    constexpr auto MySpellState = 0x1DDDDD8;
    constexpr auto CursorPosRaw = 0x1E677A8;
    constexpr auto MouseScreenVec2 = 0x1DDB028;
    constexpr auto GetPing = 0x6835A0;
    constexpr auto GetMapID = 0x29DE10;
    constexpr auto PrintChat = 0x10D8080;
} // namespace GameRuntime

namespace DrawingRuntime {
    constexpr auto WorldToScreen = 0x128EF70;
    constexpr auto HudInstance = 0x1DD7308;
    constexpr auto ViewPort = 0x1DEAE70;
    constexpr auto ViewPort2 = 0x1EA3020;
    constexpr auto Renderer = 0x1EA3018;
    constexpr auto ViewProjOffset = 0x1E8ED80;
} // namespace DrawingRuntime

namespace DrawingMatrixRuntime {
    constexpr auto ProjMatrixRelative = 0x40;
} // namespace DrawingMatrixRuntime

namespace HudRuntime {
    constexpr auto Camera = 0x18;
    constexpr auto Input = 0x28;
    constexpr auto UserData = 0x60;
    constexpr auto SpellInfo = 0x68;
    constexpr auto CameraZoom = 0x324;
    constexpr auto CameraZoomLimits = 0x310;
    constexpr auto AltZoomLimits = 0x3D0;
    constexpr auto ZoomLockFlag1 = 0x344;
    constexpr auto ZoomLockFlag2 = 0x345;
    constexpr auto MouseWorldPos = 0x34;
    constexpr auto ViewportW2S = 0x2B0;
} // namespace HudRuntime

namespace HudZoomLayout {
    constexpr auto ZoomLimitsMin = 0x24;
    constexpr auto ZoomLimitsMax = 0x28;
} // namespace HudZoomLayout

namespace HudInputLayout {
    constexpr auto SelectedObjNetId = 0x60;
} // namespace HudInputLayout

namespace ControlRuntime {
    constexpr auto IssueOrder = 0x2AFE10;
    constexpr auto CastSpellWrap = 0xBDD6B0;
    constexpr auto IsAlive = 0x2F8A40;
    constexpr auto GetSpellCastInfo = 0x293580;
    constexpr auto GetSpellSlot = 0x928BD0;
    constexpr auto GetResourceType = 0x2908C0;
    constexpr auto GetAttackDelay = 0x548420;
    constexpr auto GetAttackWindup = 0x548320;
    constexpr auto GetBoundingRadius = 0x294E30;
    constexpr auto IssueOrderFlag = 0x1D39D78;
    constexpr auto CastSpellFlag = 0x1D39D10;
    constexpr auto CastSpellSafe = 0xBDD8B0;
    constexpr auto CanAttack = 0x202900;
} // namespace ControlRuntime

namespace BasicAttackRuntime {
    constexpr auto Base = 0x2CA0;
    constexpr auto Offset1 = 0x2C0;
    constexpr auto Offset2 = 0x70;
} // namespace BasicAttackRuntime

namespace EventRuntime {
    constexpr auto CreateClientEffect = 0x5D49E0;
    constexpr auto OnCreateObject = 0x5388D0;
    constexpr auto OnGameUpdate = 0x533FE0;
    constexpr auto OnProcessSpell = 0x942270; // IDA verified: rcx=SpellBook, rdx=CastInfo, reads IsAuto@0x141, Slot@0x14C
    constexpr auto OnSpellImpact = 0x937A40;
    constexpr auto OnStopCast = 0x942300;
    constexpr auto OnFinishCast = 0x2D5B70;
    constexpr auto OnBuffAdd = 0xBF59E0;
    constexpr auto OnBuffAddHandler = 0xBF59E0;
    constexpr auto OnHeroActionStateChange = 0xEBA680;
    constexpr auto OnMinionFollowTargetNetIdChange = 0xEBDAC0;
} // namespace EventRuntime

// ── Shadow-VMT OnProcessSpell (verified in legacy NightSharp build) ──
// Game executes OnProcessSpell via vtable[HandlerIndex] on a writable heap
// dispatch slot. We deep-copy the vtable, redirect vtable[HandlerIndex] to a
// shellcode trampoline that LOCK-INCs an event counter then JMPs to the
// original function, and swap the heap slot to point at our shadow table.
// No code-page writes → safe under CRC scanners / anti-tamper.
//
// TODO (build 26.7 re-verify via IDA):
//   - VTableRVA: xref .rdata that points to WrapperRVA, subtract 35*8
//   - HandlerIndex: disasm caller, `call [rax+???]` → offset/8
//   - WrapperRVA : byte-sig 48 89 5C 24 10 56 48 83 EC 50 49 83 78 18 0F 0F 57 C0 F3 0F 7F 44 24 30
//   - VTableEntryCount: count qwords until next vtable in .rdata
namespace SpellEventVMT {
    constexpr auto VTableRVA        = 0x1928D58;
    constexpr auto HandlerIndex     = 35;
    constexpr auto VTableEntryCount = 64;
    constexpr auto WrapperRVA       = 0x1FD080;   // sub_1FD080
} // namespace SpellEventVMT

namespace NavGridRuntime {
    constexpr auto NavGrid = 0x1DDAFF0;
    constexpr auto GetCollisionFlags = 0x11DEB10;
    constexpr auto GetAiManager = 0x29CE70;
    constexpr auto GetAiManagerInner = 0x29E480;
} // namespace NavGridRuntime

namespace NavGridLayout {
    constexpr auto NavGridMgr = 0x8;
    constexpr auto MinX = 0xEC;
    constexpr auto MinZ = 0xF4;
    constexpr auto MaxX = 0xF8;
    constexpr auto MaxZ = 0x100;
    constexpr auto Data = 0x110;
    constexpr auto Width = 0x708;
    constexpr auto Height = 0x70C;
    constexpr auto Scale = 0x710;
    constexpr auto InverseScale = 0x714;
    constexpr auto GrassRegions = 0x158;
    constexpr auto CellSize = 0x10;
} // namespace NavGridLayout

namespace NavGridFlags {
    constexpr auto FlagWall = 0x1;
    constexpr auto FlagNoWalk = 0x2;
    constexpr auto FlagBrush = 0xC00;
    constexpr auto FlagSpecial = 0x1000;
} // namespace NavGridFlags

namespace SpellRuntime {
    constexpr auto SpellBookOffset = 0x3120;
    constexpr auto ActiveSpellCast = 0x3158; 
} // namespace SpellRuntime

namespace SpellBookLayout {
    constexpr auto SpellSlotArray = 0xAE0;
} // namespace SpellBookLayout

// ── Spell chain layout — IDA verification status (2026-04-17) ──────────────
//
// Direct-access fields verified by byte-pattern scan on the 26.7 dump:
//   SpellRuntime::SpellBookOffset = 0x3120         ✓ (10 `lea REG,[REG+0x3120]` hits)
//   SpellRuntime::ActiveSpellCast = 0x3158         ✓ (2 `lea` hits)
//   SpellBookLayout::SpellSlotArray = 0xAE0        ✓ (8 `mov REG,[REG+0xAE0]` hits)
//   SpellSlotLayout::SlotCooldown = 0x80           ✓ (8 `movss XMM,[REG+0x80]` hits)
//   SpellSlotLayout::SlotTotalCd = 0x88            ✓ (8 `movss XMM,[REG+0x88]` hits)
//   SpellSlotLayout::SlotActiveSpellCast = 0x118   ✓ (8 pointer reads)
//   SpellSlotLayout::SlotSpellInfo = 0x128         ✓ (8 pointer reads)
//   SpellSlotLayout::SlotSpellInput = 0x130        ✓ (8 pointer reads)
//   SpellCastInfo::IsAuto = 0x141, Slot = 0x14C    ✓ (decompiled OnProcessSpell @ 0x942270)
//   SpellData::DataResourceBase = 0x60             ✓ (OnProcessSpell `mov r8,[r8+60h]`)
//
// ⚠ SUSPECTED STALE — game accesses these fields via an indexed getter
// (param index table), not direct `[reg+disp32]` loads. A byte-pattern scan
// found 0 hits for 0x478/0x518 and only 1 for 0x568. These three constants
// are kept for source compatibility but should not be trusted without runtime
// CE verification against a live game:
//   SpellDataResourceLayout::ResCastRange    = 0x478
//   SpellDataResourceLayout::ResMissileSpeed = 0x518
//   SpellDataResourceLayout::ResLineWidth    = 0x568
// Param indices (from legacy notes): COOLDOWN=0x0C, CASTRANGE=0x0F, LINEWIDTH=0x1D.
namespace SpellSlotLayout {
    constexpr auto SlotLevel = 0x1C;
    constexpr auto SlotLevelAlt = 0x28;
    constexpr auto SlotCooldown = 0x80;
    constexpr auto SlotTotalCd = 0x88;
    constexpr auto SlotChargeTimer = 0x30;
    constexpr auto SlotCooldownExpires = 0x70;
    constexpr auto SlotStacks = 0x5C;
    constexpr auto SlotActiveSpellCast = 0x118;
    constexpr auto SlotSpellInstanceVars = 0x108;
    constexpr auto SlotSpellNameHash = 0x110;
    constexpr auto SlotSpellInfo = 0x128;
    constexpr auto SlotSpellInput = 0x130;
} // namespace SpellSlotLayout

namespace SpellDataResourceNameLayout {
    constexpr auto SpellNameStr = 0x28;
    constexpr auto SpellNameCap = 0x40;
} // namespace SpellDataResourceNameLayout

namespace SpellInputLayout {
    constexpr auto InputTargetNetId = 0x14;
    constexpr auto InputStartPos    = 0x18; // Vec3 #1 (start / caster pos)
    constexpr auto InputEndPos      = 0x24; // Vec3 #2 (primary end / target pos)
    // Additional position slots the engine mirrors — byte-pattern scan shows
    // the game reads from +0x30 (4 hits) and +0x3C (5 hits) during cast
    // dispatch, so we keep them here as named constants rather than raw
    // arithmetic (`InputEndPos + sizeof(Vec3) * k`).
    constexpr auto InputEndPos2     = 0x30; // Vec3 #3 (client/world mirror)
    constexpr auto InputEndPos3     = 0x3C; // Vec3 #4 (predicted/hitchance)
} // namespace SpellInputLayout

namespace SpellInfoLayout {
    constexpr auto InfoSpellData = 0x78; // CE verified: Info+0x60=slot backref, Info+0x78=SpellData
    constexpr auto SpellInfoNamePtr = 0x28;
    // SpellInfo mirrors the same position layout as SpellInput at the same
    // relative offsets. The cast-spell path writes positions through
    // SpellInfo (slot+0x128) while getters read through SpellInput
    // (slot+0x130) — the engine keeps them synchronized during a cast.
} // namespace SpellInfoLayout

namespace SpellDataLayout {
    constexpr auto DataSpellName = 0x80;
    constexpr auto DataManaCost = 0x5F4;
    constexpr auto DataResource = 0x8;
} // namespace SpellDataLayout

namespace SpellDataResourceLayout {
    constexpr auto DataResourceBase = 0x60;
    constexpr auto ResCastRange = 0x478;
    constexpr auto ResMissileSpeed = 0x518;
    constexpr auto ResLineWidth = 0x568;
    constexpr auto ResMaxAmmo = 0x3C0;
    constexpr auto ResCastType = 0x510;
    constexpr auto ResMissileSpec = 0x508;
    constexpr auto ResScriptName = 0x80;
    constexpr auto ResCooldownTime = 0x304;
    constexpr auto ResAmmoRecharge = 0x408;
    constexpr auto ResImgIconName = 0x2A0;
} // namespace SpellDataResourceLayout

namespace SpellCastInfoLayout {
    constexpr auto SpellData = 0x0;
    constexpr auto SrcIndex = 0x98;
    constexpr auto TargetIndex = 0x9C;
    constexpr auto StartPos = 0xD8;
    constexpr auto EndPos = 0xE4;
    constexpr auto CastPos = 0xF0;
    constexpr auto CastDelay = 0x118;
    constexpr auto IsSpell = 0x134;
    constexpr auto IsSpecialAttack = 0x13E;
    constexpr auto IsAuto = 0x141;
    constexpr auto Slot = 0x14C;
} // namespace SpellCastInfoLayout

namespace BuffManagerRuntime {
    constexpr auto BuffManagerOffset = 0x2E78;
} // namespace BuffManagerRuntime

namespace BuffManagerLayout {
    constexpr auto EntriesStart = 0x18;
    constexpr auto EntriesEnd = 0x20;
    constexpr auto EntriesCapacityEnd = 0x28;
    constexpr auto Array2Start = 0x620;
    constexpr auto Array2End = 0x628;
} // namespace BuffManagerLayout

namespace BuffEntryLayout {
    constexpr auto EntryStride = 0x10;
    constexpr auto EntryBuff = 0x0;
    constexpr auto EntryAux = 0x8;
} // namespace BuffEntryLayout

namespace BuffDataLayout {
    constexpr auto BuffType = 0xC;
    constexpr auto BuffName = 0x8;
    constexpr auto BuffScriptPtr = 0x10;
    constexpr auto BuffStartTime = 0x18;
    constexpr auto BuffEndTime = 0x1C;
    constexpr auto BuffStacks = 0x38;
    constexpr auto BuffStacksAlt = 0x3C;
} // namespace BuffDataLayout

namespace AiManagerInnerCompatLayout {
    constexpr auto Offset = 0x4220;
    constexpr auto InnerManager = 0x10;
    constexpr auto TargetPosition = 0x34;
    constexpr auto Velocity = 0x318;
    constexpr auto IsMoving = 0x31C;
    constexpr auto CurrentSegment = 0x320;
    constexpr auto PathStart = 0x330;
    constexpr auto PathEnd = 0x33C;
    constexpr auto Segments = 0x348;
    constexpr auto SegmentsCount = 0x350;
    constexpr auto HasPath = 0x354;
    constexpr auto DashSpeed = 0x360;
    constexpr auto DashMaxRangeSq = 0x374;
    constexpr auto DashDistRemaining = 0x378;
    constexpr auto DashDuration = 0x380;
    constexpr auto IsDashing = 0x384;
    constexpr auto DashEndPos = 0x3A8;
    constexpr auto ServerPos = 0x474;
    constexpr auto MoveVec3 = 0x480;
    constexpr auto DashTargetNetId = 0x48C;
    constexpr auto DashSecondaryNetId = 0x490;
    constexpr auto PreviousPos = 0x590;
} // namespace AiManagerInnerCompatLayout

namespace AiManagerNavBaseLayout {
    constexpr auto RawInnerPtr = 0x10;
    constexpr auto InnerTypePtr = 0x8;
    constexpr auto InnerTypeAdjust = 0x4;
    constexpr auto PathState = 0x300;
    constexpr auto PathEndFallback = 0x31C;
    constexpr auto Segments = 0x328;
    constexpr auto SegmentsCount = 0x330;
    constexpr auto ServerPosition = 0x454;
    constexpr auto MoveVector = 0x460;
    constexpr auto PreviousPosition = 0x570;
    constexpr auto NavModeFlag = 0x478;
    constexpr auto OrderPosition = 0x520;
    constexpr auto NavUnknownDword = 0x568;
    constexpr auto DashSpeedInner = 0x360;
    constexpr auto IsDashingInner = 0x384;
} // namespace AiManagerNavBaseLayout

namespace AiManagerPathStateLayout {
    constexpr auto CurrentIndex = 0x0;
    constexpr auto FallbackEnd = 0x1C;
    constexpr auto PointsPtr = 0x28;
    constexpr auto Count = 0x30;
} // namespace AiManagerPathStateLayout

namespace AiManagerNavDataLayout {
    constexpr auto MoveSpeed         = 0x02F8;
    constexpr auto NavFlag           = 0x02FD;
    constexpr auto ServerPosX        = 0x0310;
    constexpr auto ServerPosZ        = 0x0318;
    constexpr auto ServerPos         = 0x031C;
    constexpr auto SegmentsPtr       = 0x0328;
    constexpr auto SegmentsCount     = 0x0330;
    constexpr auto CurrentSegment    = 0x0334;
    constexpr auto DashSpeedCalc     = 0x0340;
    constexpr auto DashMaxRangeSq    = 0x0354;
    constexpr auto DashDistRemain    = 0x0358;
    constexpr auto IsDashingInner    = 0x035C;
    constexpr auto DashDuration      = 0x0360;
    constexpr auto PathStart         = 0x0388;
    constexpr auto PathEndFallback   = 0x03A0;
    constexpr auto ArrivedFlag       = 0x0450;
    constexpr auto CurrentPosX       = 0x0454;
    constexpr auto CurrentPosY       = 0x0458;
    constexpr auto CurrentPosZ       = 0x045C;
    constexpr auto DashTargetNetId   = 0x046C;
    constexpr auto DashSecondaryId   = 0x0470;
    constexpr auto MoveOverrideFlag  = 0x0474;
    constexpr auto PreviousPosX      = 0x0570;
    constexpr auto PreviousPosY      = 0x0574;
    constexpr auto PreviousPosZ      = 0x0578;
    constexpr auto VelocityX         = 0x0588;
    constexpr auto VelocityY         = 0x058C;
    constexpr auto VelocityZ         = 0x0590;
} // namespace AiManagerNavDataLayout

namespace ItemRuntime {
    // NEW chain (verified via MCP IDA on current build):
    //   obj + InventoryComponent (inline, lea not deref)
    //     component + SlotArray + index * 8 = slot ptr (SlotCount total, 8-byte ptrs)
    //       slot + ItemNode                 = item node ptr (null = empty slot)
    //         node + ItemInfo               = item info ptr
    //           info + DataItemId           = internal item id (uint32, stable hash)
    //
    // IDA evidence:
    //   sub_26B9B0 (InventoryComponent dtor): v12 = a4 + 0x50; v13 = 39; do{...}while(--v13)
    //   sub_5843D0 (GetItemIdRaw):  [rcx+0x10] -> [+0x38] -> [+0xB4]
    //   sub_594740: [rdi+rbx*8+0x4E08] = hero+0x4DB8+0x50+idx*8
    //   sub_2BE920: v5 = a4 + 0x4DB8; v6 = *(a4+0x4DB8+0x50+8*idx); if(*(v6+0x10)) ...
    constexpr auto InventoryComponent = 0x4DB8; // was ItemList=0x4D20 (dead)
    constexpr auto SlotArray          = 0x50;   // relative to InventoryComponent
    constexpr auto SlotCount          = 39;     // 0x27, from dtor loop counter
    constexpr auto ItemNode           = 0x10;   // relative to slot (was SlotInfo)
    constexpr auto ItemInfo           = 0x38;   // relative to ItemNode (was InfoData)
    constexpr auto DataItemId         = 0xB4;   // relative to ItemInfo (internal id)

    // Legacy aliases kept for source compatibility during migration.
    constexpr auto ItemList = InventoryComponent;
    constexpr auto SlotInfo = ItemNode;
    constexpr auto InfoData = ItemInfo;

    // Slot classes (verified in sub_590710: visible inventory enumerates 0..6)
    constexpr auto SlotItemBegin = 0;  // first regular item slot
    constexpr auto SlotItemEnd   = 5;  // last regular item slot (inclusive)
    constexpr auto SlotTrinket   = 6;  // trinket/ward slot
    constexpr auto SlotVisibleCount = 7; // slots 0..6 (visible inventory)

    // Item stat offsets relative to ItemInfo — still need CE re-verify on current build
    // (kept as-is from the previous snapshot; values were tied to the old InfoData
    // chain which had the same 0x38 offset, so they may still be correct).
    constexpr auto InfoStacks = 0x64;
    constexpr auto DataAbilityHaste = 0x160;
    constexpr auto DataHealth = 0x164;
    constexpr auto DataArmor = 0x1B4;
    constexpr auto DataMR = 0x1BC;
    constexpr auto DataAD = 0x1D8;
    constexpr auto DataAP = 0x1E0;
    constexpr auto DataAtkSpeedMult = 0x20C;
} // namespace ItemRuntime

namespace TypeFlagsRuntime {
    constexpr auto IsObjectAI = 0x400;
    constexpr auto Minion = 0x800;
    constexpr auto Hero = 0x1000;
    constexpr auto Turret = 0x2000;
    constexpr auto Plant = 0x8000;
    constexpr auto IsRecalling = 0x4000;
} // namespace TypeFlagsRuntime

namespace MinionClassRuntime {
    constexpr auto TypeOffset = 0x4CA9; // IDA confirmed: 0F B6 81 A9 4C 00 00 at 0x2AC3D0
    constexpr auto Unset = 0x0;
    constexpr auto Pet = 0x1;
    constexpr auto JungleMonster = 0x2;
    constexpr auto TeamMinion = 0x3;
    constexpr auto MeleeLaneMinion = 0x4;
    constexpr auto RangedLaneMinion = 0x5;
    constexpr auto SiegeLaneMinion = 0x6;
    constexpr auto SuperLaneMinion = 0x7;
    constexpr auto FollowTargetNetId = 0x6A8; 
} // namespace MinionClassRuntime

namespace JungleTypeRuntime {
    constexpr auto TypeOffset = 0x4AB4; // IDA confirmed: sub_2A1780 reads *(obj+0x4AB4)
    constexpr auto Normal = 0x0;
    constexpr auto Baron = 0x1;
    constexpr auto Dragon = 0x2;
} // namespace JungleTypeRuntime

namespace ClassificationRuntime {
    constexpr auto CompareTypeFlags = 0x2ACC10;
    constexpr auto IsJungleMonster = 0x2AC060;
    constexpr auto GetJungleType = 0x686FA0;
    constexpr auto IsClone = 0x2AAF10;
    constexpr auto IsBuilding = 0x31C3E0;
    constexpr auto IsDead = 0x2AB1B0;
    constexpr auto IsVulnerable = 0x2ABE80;
    constexpr auto IsDragon = 0x2AB470;
    constexpr auto IsElderDragon = 0x2AB4E0;
    constexpr auto IsBaron = 0x2AA840;
    constexpr auto IsSelectable = 0x21C2F0;
    constexpr auto IsFleeing = 0x115A800;
    constexpr auto IsNoRender = 0x219540;
} // namespace ClassificationRuntime

namespace UnitQueryRuntime {
    constexpr auto IsTargetableByUnit = 0x2AE350;
    constexpr auto HasBuffOfType = 0x2A5FA0;
    constexpr auto GetGoldRedirectTgt = 0x209B60;
} // namespace UnitQueryRuntime

namespace AnimationLayout {
    constexpr auto CharacterData = 0x40C8;
    constexpr auto Component = 0x4488; // CE+IDA confirmed +0x38
    constexpr auto Queue = 0x4960; // CE+IDA confirmed +0x38
    constexpr auto QueueEnd = 0x4968; // CE+IDA confirmed +0x38
    constexpr auto QueueCapacityEnd = 0x4970; // +0x38, CE uncertain
    constexpr auto SkinIndex = 0x146;
    constexpr auto CharacterDataResource = 0x60;
    constexpr auto VariantEntries = 0x240;
    constexpr auto VariantEntryCount = 0x248;
    constexpr auto FallbackNamePtr = 0x250;
    constexpr auto FallbackState = 0x260;
    constexpr auto VariantEntryStride = 0xB0;
    constexpr auto VariantNamePtr = 0x8;
    constexpr auto VariantState = 0x18;
} // namespace AnimationLayout

// === Per-class object namespaces (base fields + class-specific) ===

namespace All {
    constexpr auto Index = 0x10;
    constexpr auto Team = 0x259; // IDA+CE: byte team index at obj+0x259, lookup via global table
    constexpr auto Name = 0x68;
    constexpr auto NetId = 0xCC;
    constexpr auto Dead = 0x250;
    constexpr auto Position = 0x25C;
    constexpr auto Visibility = 0x2E0;
    constexpr auto Visible = 0x308;
    constexpr auto IsInvulnerable = 0x5A0;
    constexpr auto RecallState = 0xF48;
    constexpr auto Radius = 0x6F8;
    constexpr auto CharacterData = 0x40C8;
    constexpr auto CharacterName = 0x4360;
    constexpr auto Direction = 0x21D8;
    constexpr auto EffectEmitterHandle = 0x258;
    constexpr auto MissileClientHandle = 0x2D8;
    constexpr auto ItemList = 0x4DB8; // NEW: InventoryComponent base (was 0x4D20)
} // namespace All

namespace AttackableUnit {
    constexpr auto HP = 0x1080;
    constexpr auto MaxHP = 0x10A8;
    constexpr auto HPMaxPenalty = 0x10D0;
    constexpr auto AllShield = 0x1120;
    constexpr auto PhysicalShield = 0x1148;
    constexpr auto MagicalShield = 0x1170;
    constexpr auto ChampSpecific = 0x1198;
    constexpr auto InHealAllied = 0x11C0;
    constexpr auto InHealEnemy = 0x11E8;
    constexpr auto InDamage = 0x1210;
    constexpr auto StopShieldFade = 0x1238;
    constexpr auto IsTargetable = 0xED0;
    constexpr auto TargetableFlags = 0xEF8;
    constexpr auto ActionState1 = 0x1470;
    constexpr auto ActionState2 = 0x14A8;
} // namespace AttackableUnit

namespace AIHeroClient {
    constexpr auto MP = 0x360;
    constexpr auto MaxMP = 0x388;
    constexpr auto PAR = 0xE00;
    constexpr auto MaxPAR = 0xE28;
    constexpr auto SAR = 0x108;
    constexpr auto MaxSAR = 0x130;
    constexpr auto PhysDmgPercent = 0xEB0; // +0x38
    constexpr auto MagicDmgPercent = 0xED8; // +0x38
    constexpr auto AbilityHaste = 0x1BE8; // +0x38
    constexpr auto FlatPhysicalDmgMod = 0x1D00; // +0x38, CE=7.2
    constexpr auto AttackSpeedMod = 0x1E68; // +0x38, CE=1.1
    constexpr auto PercentAttackSpeedMod = 0x1E90; // +0x38, CE=0.1
    constexpr auto BaseAttackDamage = 0x1F08; // +0x38, CE=59.0
    constexpr auto BaseAtkDmgSansScale = 0x1F30; // +0x38
    constexpr auto FlatBaseAtkDmgMod = 0x1F58; // +0x38
    constexpr auto PercentBaseAtkDmgMod = 0x1F80; // +0x38
    constexpr auto BaseAbilityDamage = 0x1FA8; // +0x38
    constexpr auto CritDamageMultiplier = 0x1FD0; // +0x38
    constexpr auto Dodge = 0x2020; // +0x38
    constexpr auto Crit = 0x2048; // +0x38
    constexpr auto Armor = 0x2098; // +0x38, CE=26.0
    constexpr auto BonusArmor = 0x20C0; // +0x38
    constexpr auto SpellBlock = 0x20E8; // +0x38
    constexpr auto BonusSpellBlock = 0x2110; // +0x38
    constexpr auto HPRegenRate = 0x2138; // +0x38, CE=0.8
    constexpr auto BaseHPRegenRate = 0x2160; // +0x38, CE=0.8
    constexpr auto MoveSpeed = 0x2188; // +0x38, CE=522.5
    constexpr auto AttackRange = 0x21D8; // +0x38, CE=525.0
    constexpr auto FlatArmorPen = 0x2250; // +0x38
    constexpr auto PhysicalLethality = 0x2278; // +0x38
    constexpr auto PercentArmorPen = 0x22A0; // +0x38
    constexpr auto PercentBonusArmorPen = 0x22C8; // +0x38
    constexpr auto FlatMagicPen = 0x2340; // +0x38
    constexpr auto MagicLethality = 0x2368; // +0x38
    constexpr auto PercentMagicPen = 0x2390; // +0x38
    constexpr auto PercentBonusMagicPen = 0x23B8; // +0x38
    constexpr auto PercentLifeSteal = 0x23E0; // +0x38
    constexpr auto PercentSpellVamp = 0x2408; // +0x38
    constexpr auto PercentOmnivamp = 0x2430; // +0x38
    constexpr auto PercentCCReduction = 0x24A8; // +0x38
    constexpr auto FlatBaseAttackSpeedMod = 0x25E8; // +0x38
    constexpr auto Gold = 0x2868; // IDA+CE confirmed: registrar [r14+0x2868], CE=930.4
    constexpr auto GoldTotal = 0x2890; // IDA+CE confirmed: registrar [r14+0x2890]
    constexpr auto Exp = 0x4D28; // +0x38
    constexpr auto LevelRef = 0x4D50; // +0x38, CE=1
    constexpr auto LevelUpPoints = 0x4DB0; // +0x38, CE=1
    constexpr auto VisionScore = 0x5618; // +0x38, IDA confirmed
    constexpr auto ShutdownValue = 0x5640; // +0x38, IDA confirmed
    constexpr auto BaseGoldOnDeath = 0x5668; // +0x38, CE=400.0
    constexpr auto NeutralMinionsKilled = 0x5690; // +0x38
} // namespace AIHeroClient

namespace MissileClient {
    constexpr auto SpellDataPtr = 0x128;
    constexpr auto CastInfoBase = 0x2C0;
    constexpr auto SpellName = 0x2E0;
    constexpr auto MissileName = 0x308;
    constexpr auto CasterNetId = 0x358;
    constexpr auto TargetNetId = 0x35C;
    constexpr auto MissileNetId = 0x364;
    constexpr auto StartPos = 0x330;
    constexpr auto EndPos = 0x33C;
    constexpr auto CastEndPos = 0x34C;
    constexpr auto Position = 0x25C;
} // namespace MissileClient

// === Hack / Bypass ===

namespace GadgetRuntime {
    constexpr auto ThreadTrampoline = 0x18D1A7C;
} // namespace GadgetRuntime

namespace DirectInputRuntime {
    constexpr auto KeyboardInput = 0x1170AA0;
    constexpr auto MouseInput = 0x1170CB0;
    constexpr auto KeyboardDevice = 0x1E814F8;
    constexpr auto KeyboardBuffer = 0x1E81508;
    constexpr auto KeyboardCount  = 0x1E81528;
    constexpr auto KeyboardFlag   = 0x1E81548;
    constexpr auto MouseDevice    = 0x1E81500;
    constexpr auto MouseBuffer    = 0x1E81510;
    constexpr auto MouseCount     = 0x1E81538;
    constexpr auto VT_GetDeviceState = 0x48;
    constexpr auto VT_GetDeviceData  = 0x50;
} // namespace DirectInputRuntime

namespace ZoomRuntime {
    constexpr auto HudToCameraPtr    = 0x18;
    constexpr auto CurrentZoom       = 0x324;
    constexpr auto ZoomConfigPtr     = 0x3D0;
    constexpr auto ZoomFallbackPtr   = 0x310;
    constexpr auto DisableZoomClamp  = 0x345;
    constexpr auto ZoomClampFlag     = 0x344;
    constexpr auto ZC_MinZoom        = 0x24;
    constexpr auto ZC_MaxZoom        = 0x28;
    constexpr auto HardcodedMaxZoom  = 0x1920A24; // IDA xref verified
    constexpr auto ZoomEnableConfig  = 0x1E49380; // IDA xref verified
} // namespace ZoomRuntime

namespace SkinRuntime {
    constexpr auto SkinNetID         = 0x1440;
    constexpr auto SkinName          = 0x1448;
    constexpr auto ModelName         = 0x1468;
    constexpr auto SkinChangeFlag    = 0x1488;
    constexpr auto SkinParam1        = 0x148C;
    constexpr auto SkinParam2        = 0x1490;
} // namespace SkinRuntime

namespace ShopRuntime {
    constexpr auto IsShopOpen        = 0x1DD41D8; // IDA: mov cs:dword, eax in sub_AA900
} // namespace ShopRuntime

namespace EventSpellCastInfoLayout {
    constexpr auto SCI_CasterNetId   = 0x00A0;
    constexpr auto SCI_SpellSlotShort = 0x0146;
    constexpr auto SCI_SpellSlotInt  = 0x0154;
    constexpr auto SCI_IsStopCast    = 0x01AC;
    constexpr auto SCI_CastState     = 0x0198;
    constexpr auto SCI_CastData      = 0x01E8;
} // namespace EventSpellCastInfoLayout

namespace NavGridCellLayout {
    constexpr auto CellOverlay       = 0x00;
    constexpr auto CellFlags         = 0x08;
    constexpr auto OverlayFlagsOff   = 0x06;
    constexpr auto CellStride        = 16;
    constexpr auto CELL_WALL         = 0x0002;
    constexpr auto CELL_BRUSH        = 0x0004;
    constexpr auto CELL_WATER        = 0x0010;
    constexpr auto CELL_BUILDING     = 0x0040;
    constexpr auto CELL_VISION       = 0x0080;
    constexpr auto CELL_PASSABILITY  = 0x0C00;
    constexpr auto HalfCellSize      = 0x0718;
} // namespace NavGridCellLayout

}
