#pragma once
// Generated native evade-spell database for KuroEvade.

#include "EvadeSpellData.h"

#include <vector>

namespace Plugins::KuroEvade::Generated {

inline std::vector<EvadeSpellData> BuildEvadeSpellData() {
    std::vector<EvadeSpellData> data;
    data.reserve(83);
    EvadeSpellData e;
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Aatrox";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 300;
    e.Name = "Aatrox E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 800;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Ahri";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 500;
    e.Name = "Ahri R";
    e.Slot = SDK::SpellSlot::R;
    e.Speed = 1500;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Akali";
    e.CheckSpellName = "AkaliE";
    e.DangerLevel = 3;
    e.Delay = 250;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.IsReversed = true;
    e.MaxRange = 395;
    e.Name = "Akali E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1400;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Alistar";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 650;
    e.Name = "Alistar W";
    e.Slot = SDK::SpellSlot::W;
    e.Speed = 1500;
    e.ValidTargets = {SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Blitzcrank";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Blitzcrank W";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Braum";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 650;
    e.Name = "Braum W";
    e.Slot = SDK::SpellSlot::W;
    e.Speed = 1500;
    e.ValidTargets = {SpellTargets::AllyChampions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Caitlyn";
    e.DangerLevel = 4;
    e.Delay = 250;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.IsReversed = true;
    e.MaxRange = 390;
    e.Name = "Caitlyn E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1000;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Corki";
    e.CheckSpellName = "CarpetBomb";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 600;
    e.MinRange = 300;
    e.Name = "Corki W";
    e.Slot = SDK::SpellSlot::W;
    e.Speed = 975;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Corki";
    e.CheckSpellName = "CarpetBombMega";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.MaxRange = 1900;
    e.Name = "Corki W Mega";
    e.Slot = SDK::SpellSlot::W;
    e.Speed = 1500;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Draven";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Draven W";
    e.Slot = SDK::SpellSlot::W;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Ekko";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.MaxRange = 350;
    e.Name = "Ekko E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1150;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Ekko";
    e.DangerLevel = 3;
    e.Delay = 250;
    e.EvadeTypeValue = EvadeType::Blink;
    e.IsInfrontTarget = true;
    e.IsSpecial = true;
    e.MaxRange = 500;
    e.Name = "Ekko E Attack";
    e.Slot = SDK::SpellSlot::E;
    e.ValidTargets = {SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Ekko";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Blink;
    e.IsSpecial = true;
    e.MaxRange = 20000;
    e.Name = "Ekko R";
    e.Slot = SDK::SpellSlot::R;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Elise";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Invulnerability;
    e.IsSpecial = true;
    e.Name = "Elise E";
    e.Slot = SDK::SpellSlot::E;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Ezreal";
    e.DangerLevel = 4;
    e.Delay = 250;
    e.EvadeTypeValue = EvadeType::Blink;
    e.MaxRange = 475;
    e.Name = "Ezreal E";
    e.Slot = SDK::SpellSlot::E;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Fiora";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 400;
    e.Name = "Fiora Q";
    e.Slot = SDK::SpellSlot::Q;
    e.Speed = 1100;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Fiora";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Invulnerability;
    e.Name = "Fiora W";
    e.Slot = SDK::SpellSlot::W;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Fizz";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 550;
    e.Name = "Fizz Q";
    e.Slot = SDK::SpellSlot::Q;
    e.Speed = 1390;
    e.ValidTargets = {SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Fizz";
    e.CheckSpellName = "FizzE";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Invulnerability;
    e.Name = "Fizz E";
    e.Slot = SDK::SpellSlot::E;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Garen";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Garen Q";
    e.Slot = SDK::SpellSlot::Q;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Gnar";
    e.CheckSpellName = "GnarE";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 475;
    e.Name = "Gnar E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 900;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Gnar";
    e.CheckSpellName = "GnarBigE";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 600;
    e.Name = "Gnar Big E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 900;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Gragas";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.MaxRange = 600;
    e.Name = "Gragas E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 910;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Graves";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 425;
    e.Name = "Graves E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1140;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Irelia";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.IsBehindTarget = true;
    e.IsEnabled = false;
    e.MaxRange = 600;
    e.Name = "Irelia Q";
    e.Slot = SDK::SpellSlot::Q;
    e.Speed = 1835;
    e.ValidTargets = {SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Jax";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 700;
    e.Name = "Jax Q";
    e.Slot = SDK::SpellSlot::Q;
    e.Speed = 1400;
    e.ValidTargets = {SpellTargets::AllyChampions, SpellTargets::AllyMinions, SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Jayce";
    e.CheckSpellName = "JayceToTheSkies";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.IsInfrontTarget = true;
    e.MaxRange = 600;
    e.Name = "Jayce Q";
    e.Slot = SDK::SpellSlot::Q;
    e.Speed = 800;
    e.ValidTargets = {SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Kaisa";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.IsEnabled = false;
    e.HasMoveSpeedAmount = true;
    e.Name = "Kaisa E";
    e.Slot = SDK::SpellSlot::E;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Karma";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Karma E";
    e.Slot = SDK::SpellSlot::E;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Kassadin";
    e.DangerLevel = 1;
    e.Delay = 250;
    e.EvadeTypeValue = EvadeType::Blink;
    e.MaxRange = 500;
    e.Name = "Kassadin R";
    e.Slot = SDK::SpellSlot::R;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Katarina";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Katarina W";
    e.Slot = SDK::SpellSlot::W;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Katarina";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Blink;
    e.IsSpecial = true;
    e.MaxRange = 725;
    e.Name = "Katarina E";
    e.Slot = SDK::SpellSlot::E;
    e.ValidTargets = {SpellTargets::AllyChampions, SpellTargets::AllyMinions, SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Kayle";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Kayle W";
    e.Slot = SDK::SpellSlot::W;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Kennen";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Kennen E";
    e.Slot = SDK::SpellSlot::E;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Khazix";
    e.CheckSpellName = "KhazixE";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 700;
    e.Name = "Khazix E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1260;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Khazix";
    e.CheckSpellName = "KhazixELong";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 900;
    e.Name = "Khazix E Long";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1210;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Khazix";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Khazix R";
    e.Slot = SDK::SpellSlot::R;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Kindred";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 325;
    e.Name = "Kindred Q";
    e.Slot = SDK::SpellSlot::Q;
    e.Speed = 830;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Kled";
    e.CheckSpellName = "KledE";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.MaxRange = 600;
    e.Name = "Kled E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 945;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Leblanc";
    e.CheckSpellName = "LeblancW";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 600;
    e.Name = "Leblanc W";
    e.Slot = SDK::SpellSlot::W;
    e.Speed = 1450;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Leblanc";
    e.CheckSpellName = "LeblancRW";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 600;
    e.Name = "Leblanc RW";
    e.Slot = SDK::SpellSlot::R;
    e.Speed = 145;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "LeeSin";
    e.CheckSpellName = "BlindMonkWOne";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 700;
    e.Name = "LeeSin W";
    e.Slot = SDK::SpellSlot::W;
    e.Speed = 2000;
    e.ValidTargets = {SpellTargets::AllyChampions};
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Lucian";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 445;
    e.Name = "Lucian E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1350;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Lulu";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Lulu W";
    e.Slot = SDK::SpellSlot::W;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Maokai";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Invulnerability;
    e.MaxRange = 525;
    e.Name = "Maokai W";
    e.Slot = SDK::SpellSlot::W;
    e.ValidTargets = {SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "MasterYi";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Invulnerability;
    e.MaxRange = 600;
    e.Name = "MasterYi Q";
    e.Slot = SDK::SpellSlot::Q;
    e.ValidTargets = {SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "MonkeyKing";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 650;
    e.Name = "MonkeyKing E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1395;
    e.ValidTargets = {SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Nidalee";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.IsSpecial = true;
    e.MaxRange = 400;
    e.Name = "Nidalee W";
    e.Slot = SDK::SpellSlot::W;
    e.Speed = 940;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Nocturne";
    e.DangerLevel = 1;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::SpellShield;
    e.Name = "Nocturne W";
    e.Slot = SDK::SpellSlot::W;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Pantheon";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.IsInfrontTarget = true;
    e.MaxRange = 600;
    e.Name = "Pantheon W";
    e.Slot = SDK::SpellSlot::W;
    e.Speed = 1000;
    e.ValidTargets = {SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Poppy";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Poppy W";
    e.Slot = SDK::SpellSlot::W;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Pyke";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.MaxRange = 550;
    e.Name = "Pyke E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 2000;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Rakan";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 650;
    e.Name = "Rakan W";
    e.Slot = SDK::SpellSlot::W;
    e.Speed = 1500;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Rakan";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.IsBehindTarget = true;
    e.MaxRange = 650;
    e.Name = "Rakan E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1800;
    e.ValidTargets = {SpellTargets::AllyChampions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Riven";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.IsSpecial = true;
    e.MaxRange = 275;
    e.Name = "Riven Q";
    e.Slot = SDK::SpellSlot::Q;
    e.Speed = 780;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Riven";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.MaxRange = 250;
    e.Name = "Riven E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1190;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Rumble";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Rumble W";
    e.Slot = SDK::SpellSlot::W;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Sejuani";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 650;
    e.Name = "Sejuani Q";
    e.Slot = SDK::SpellSlot::Q;
    e.Speed = 1000;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Shaco";
    e.DangerLevel = 3;
    e.Delay = 250;
    e.EvadeTypeValue = EvadeType::Blink;
    e.MaxRange = 400;
    e.Name = "Shaco Q";
    e.Slot = SDK::SpellSlot::Q;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Shen";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 600;
    e.Name = "Shen E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1155;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Shyvana";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Shyvana W";
    e.Slot = SDK::SpellSlot::W;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Sivir";
    e.DangerLevel = 1;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::SpellShield;
    e.Name = "Sivir E";
    e.Slot = SDK::SpellSlot::E;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Sona";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Sona E";
    e.Slot = SDK::SpellSlot::E;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Sylas";
    e.CheckSpellName = "SylasE";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 400;
    e.Name = "Sylas E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1450;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Tristana";
    e.DangerLevel = 4;
    e.Delay = 250;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 900;
    e.Name = "Tristana W";
    e.Slot = SDK::SpellSlot::W;
    e.Speed = 1110;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Tryndamere";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 650;
    e.Name = "Tryndamere E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 900;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Udyr";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Udyr E";
    e.Slot = SDK::SpellSlot::E;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Vayne";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.MaxRange = 300;
    e.Name = "Vayne Q";
    e.Slot = SDK::SpellSlot::Q;
    e.Speed = 830;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Zeri";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.MaxRange = 300;
    e.Name = "Zeri E";
    e.Slot = SDK::SpellSlot::Unknown;
    e.Speed = 850;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Vladimir";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Invulnerability;
    e.Name = "Vladimir W";
    e.Slot = SDK::SpellSlot::W;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Volibear";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Volibear Q";
    e.Slot = SDK::SpellSlot::Q;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Xayah";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Invulnerability;
    e.Name = "Xayah R";
    e.Slot = SDK::SpellSlot::R;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "XinZhao";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.IsInfrontTarget = true;
    e.MaxRange = 650;
    e.Name = "XinZhao E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 3000;
    e.ValidTargets = {SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "Yasuo";
    e.DangerLevel = 3;
    e.Delay = 250;
    e.EvadeTypeValue = EvadeType::WindWall;
    e.Name = "Yasuo W";
    e.Slot = SDK::SpellSlot::W;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Yasuo";
    e.DangerLevel = 2;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.FixedRange = true;
    e.MaxRange = 475;
    e.Name = "Yasuo E";
    e.Slot = SDK::SpellSlot::E;
    e.Speed = 1000;
    e.ValidTargets = {SpellTargets::EnemyChampions, SpellTargets::EnemyMinions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Target;
    e.ChampionName = "Yuumi";
    e.CheckSpellName = "YuumiW";
    e.DangerLevel = 2;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Dash;
    e.MaxRange = 700;
    e.Name = "Yuumi W";
    e.Slot = SDK::SpellSlot::W;
    e.Speed = 1500;
    e.ValidTargets = {SpellTargets::AllyChampions};
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Yuumi";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.IsSpecial = true;
    e.HasMoveSpeedAmount = true;
    e.Name = "Yuumi E";
    e.Slot = SDK::SpellSlot::E;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "Zilean";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.HasMoveSpeedAmount = true;
    e.Name = "Zilean E";
    e.Slot = SDK::SpellSlot::E;
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "AllChampions";
    e.DangerLevel = 3;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::MovementSpeedBuff;
    e.IsItem = true;
    e.ItemId = 3142;
    e.HasMoveSpeedAmount = true;
    e.Name = "Youmuu's Ghostblade";
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "AllChampions";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Invulnerability;
    e.IsItem = true;
    e.ItemId = 3157;
    e.Name = "Zhonya's Hourglass";
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "AllChampions";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Invulnerability;
    e.IsItem = true;
    e.ItemId = 2420;
    e.Name = "Stopwatch";
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Self;
    e.ChampionName = "AllChampions";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Invulnerability;
    e.IsItem = true;
    e.ItemId = 2423;
    e.Name = "PerfectTime Stopwatch";
    e.IndexUseWhen = 0;
    data.push_back(e);
    e = {};
    e.CastTypeValue = CastType::Position;
    e.ChampionName = "AllChampions";
    e.CheckSpellName = "SummonerFlash";
    e.DangerLevel = 4;
    e.Delay = 50;
    e.EvadeTypeValue = EvadeType::Blink;
    e.IsSummonerSpell = true;
    e.MaxRange = 425;
    e.Name = "Flash";
    e.Slot = SDK::SpellSlot::Unknown;
    e.IndexUseWhen = 0;
    data.push_back(e);
    return data;
}

inline const std::vector<EvadeSpellData>& EvadeSpellDataList() {
    static const std::vector<EvadeSpellData> data = BuildEvadeSpellData();
    return data;
}

} // namespace Plugins::KuroEvade::Generated
