#pragma once
// Generated native spell windup database for KuroEvade.

#include "../../../SDK/SDK.h"

#include <string>
#include <vector>

namespace Plugins::KuroEvade::Generated {

struct SpellWindupEntry {
    std::string ChampionName;
    std::string SpellName;
    SDK::SpellSlot Slot = SDK::SpellSlot::Unknown;
};

inline std::vector<SpellWindupEntry> BuildSpellWindupData() {
    std::vector<SpellWindupEntry> data;
    data.reserve(327);
    SpellWindupEntry e;
    e = {};
    e.ChampionName = "Aatrox";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Aatrox";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ahri";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ahri";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Akali";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Alistar";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Amumu";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Amumu";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Anivia";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Anivia";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Anivia";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Annie";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Annie";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Annie";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ashe";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ashe";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ashe";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ashe";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "AurelionSol";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Azir";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Azir";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Azir";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Bard";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Bard";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Bard";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Bard";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Blitzcrank";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Blitzcrank";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Brand";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Brand";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Brand";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Brand";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Braum";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Braum";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Caitlyn";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Caitlyn";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Caitlyn";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Cassiopeia";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Cassiopeia";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Cassiopeia";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Cassiopeia";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Chogath";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Chogath";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Chogath";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Corki";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Corki";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Darius";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Darius";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Diana";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Diana";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Diana";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Draven";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Draven";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "DrMundo";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ekko";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ekko";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Elise";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Elise";
    e.SpellName = "EliseHumanW";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Elise";
    e.SpellName = "EliseHumanE";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Evelynn";
    e.SpellName = "EvelynnQ";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Evelynn";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Evelynn";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ezreal";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ezreal";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ezreal";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "FiddleSticks";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "FiddleSticks";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "FiddleSticks";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "FiddleSticks";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Fizz";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Fizz";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Galio";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Galio";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Galio";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Galio";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Gangplank";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Gangplank";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Gangplank";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Gangplank";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Garen";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Gnar";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Gnar";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Gnar";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Gragas";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Gragas";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Graves";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Graves";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Graves";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Heimerdinger";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Heimerdinger";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Heimerdinger";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Illaoi";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Illaoi";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Illaoi";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Irelia";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ivern";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ivern";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ivern";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Janna";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Janna";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "JarvanIV";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "JarvanIV";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "JarvanIV";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Jayce";
    e.SpellName = "JayceShockBlast";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Jayce";
    e.SpellName = "JayceThunderingBlow";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Jhin";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Jhin";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Jhin";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Jhin";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Jinx";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Jinx";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kaisa";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kalista";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kalista";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kalista";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Karma";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Karma";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Karthus";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Karthus";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Karthus";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kassadin";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kassadin";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Katarina";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Katarina";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kayle";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kayn";
    e.SpellName = "KaynW";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kennen";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kennen";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kennen";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Khazix";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Khazix";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kindred";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kindred";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Kled";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "KogMaw";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "KogMaw";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "KogMaw";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "KogMaw";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Leblanc";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Leblanc";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Leblanc";
    e.SpellName = "LeblancRQ";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Leblanc";
    e.SpellName = "LeblancRE";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "LeeSin";
    e.SpellName = "BlindMonkQOne";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "LeeSin";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "LeeSin";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Leona";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Leona";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Lissandra";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Lissandra";
    e.SpellName = "LissandraE";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Lucian";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Lucian";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Lulu";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Lux";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Lux";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Lux";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Lux";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Malphite";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Malphite";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Malzahar";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Malzahar";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Malzahar";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Maokai";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Maokai";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Maokai";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "MissFortune";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "MissFortune";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "MissFortune";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Mordekaiser";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Mordekaiser";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Morgana";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Morgana";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Morgana";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nami";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nami";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nami";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nasus";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nasus";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nasus";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nautilus";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nautilus";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nautilus";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Neeko";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Neeko";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Neeko";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nidalee";
    e.SpellName = "JavelinToss";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nidalee";
    e.SpellName = "Bushwhack";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nidalee";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nocturne";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nunu";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Nunu";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Olaf";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Olaf";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Orianna";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ornn";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ornn";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ornn";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ornn";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Pantheon";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Pantheon";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Pantheon";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Poppy";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Poppy";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Poppy";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Pyke";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Pyke";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Quinn";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Quinn";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Quinn";
    e.SpellName = "QuinnR";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Rakan";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Rammus";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Rammus";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "RekSai";
    e.SpellName = "RekSaiQBurrowed";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "RekSai";
    e.SpellName = "RekSaiE";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Renekton";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Renekton";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Rengar";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Riven";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Riven";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Rumble";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Rumble";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ryze";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ryze";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ryze";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Sejuani";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Sejuani";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Shaco";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Shaco";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Shaco";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Shen";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Shyvana";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Shyvana";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Singed";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Singed";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Sion";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Sion";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Sivir";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Sivir";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Skarner";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Skarner";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Sona";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Soraka";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Soraka";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Soraka";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Soraka";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Swain";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Swain";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Swain";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Sylas";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Sylas";
    e.SpellName = "SylasE2";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Sylas";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Syndra";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Syndra";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "TahmKench";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "TahmKench";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "TahmKench";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "TahmKench";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Taliyah";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Taliyah";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Taliyah";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Taliyah";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Talon";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Taric";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Taric";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Taric";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Teemo";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Teemo";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Thresh";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Thresh";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Thresh";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Thresh";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Tristana";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Tristana";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Tristana";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Trundle";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Trundle";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Tryndamere";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "TwistedFate";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "TwistedFate";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Twitch";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Twitch";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Twitch";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Urgot";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Urgot";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Varus";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Varus";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Vayne";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Veigar";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Veigar";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Veigar";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Veigar";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Velkoz";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Velkoz";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Velkoz";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Vi";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Vi";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Viktor";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Viktor";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Viktor";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Vladimir";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Volibear";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Volibear";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Warwick";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Warwick";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Warwick";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Xayah";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Xayah";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Xerath";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Xerath";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Xerath";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "XinZhao";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "XinZhao";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Yasuo";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Yorick";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Yorick";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Yorick";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Zac";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Zac";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Zed";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ziggs";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ziggs";
    e.Slot = SDK::SpellSlot::W;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ziggs";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Ziggs";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    e = {};
    e.ChampionName = "Zilean";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Zoe";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Zyra";
    e.Slot = SDK::SpellSlot::Q;
    data.push_back(e);
    e = {};
    e.ChampionName = "Zyra";
    e.Slot = SDK::SpellSlot::E;
    data.push_back(e);
    e = {};
    e.ChampionName = "Zyra";
    e.Slot = SDK::SpellSlot::R;
    data.push_back(e);
    return data;
}

inline const std::vector<SpellWindupEntry>& SpellWindupData() {
    static const std::vector<SpellWindupEntry> data = BuildSpellWindupData();
    return data;
}

} // namespace Plugins::KuroEvade::Generated
