#pragma once

// Projectile-wall collision is independent from unit collision. This compact
// database preserves that distinction for missiles that pass through units
// (Ezreal R, Ahri Q, etc.) while also filling the wall profile omitted by many
// legacy unit-collision entries.

#include <string>

namespace Plugins::KuroEvade::Database {

inline bool IsProjectileWallBlocked(const std::string& missileName) {
    if (missileName.empty()) {
        return false;
    }
    static constexpr const char* names[] = {
        "AatroxW",
        "AhriOrbMissile",
        "AhriOrbReturn",
        "AhriSeduceMissile",
        "AkaliEMis",
        "AkshanQMissile",
        "ApheliosCalibrumQMis",
        "ApheliosRMis",
        "BlindMonkQOne",
        "BrandQMissile",
        "BraumQMissile",
        "BraumRMissile",
        "BriarRMissile",
        "CaitlynEntrapmentMissile",
        "CaitlynPiltoverPeacemakerMissile",
        "DarkBindingMissile",
        "DianaQMissile",
        "DravenDoubleShotMissile",
        "DravenRCast",
        "DrMundoQMissile",
        "EkkoQMis",
        "EliseHumanE",
        "EnchantedCrystalArrow",
        "EvelynnQLineMis",
        "EzrealQ",
        "EzrealR",
        "EzrealW",
        "FioraWMissile",
        "FizzRMissile",
        "FlashFrostSpell",
        "GalioQMissileIn",
        "GnarBigQMissile",
        "GnarQMissile",
        "GragasQMissile",
        "GragasRMissile",
        "GravesClusterShotAttack",
        "GravesQLineMissile",
        "GravesUltimateMissile",
        "GwenRMissile",
        "HeimerdingerEExplosion",
        "HeimerdingerWMaxAttack",
        "HowlingGaleSpell",
        "HweiEQMissile",
        "HweiQQMissile",
        "HweiRMissile",
        "IllaoiEMis",
        "IreliaEMissile",
        "IreliaR",
        "IvernQ",
        "JavelinToss",
        "JhinRShotMis",
        "JhinWMissile",
        "JinxR",
        "JinxWMissile",
        "KarmaQMissile",
        "KarmaQMissileMantra",
        "KaisaWMissile",
        "KennenShurikenHurlMissile",
        "KhazixWMissile",
        "KledQMissile",
        "KogMawQVMissile",
        "KogMawVoidOozeMissile",
        "LeblancEMissile",
        "LeblancREMissile",
        "LeonaZenithBladeMissile",
        "LilliaE",
        "LilliaERollingMissile",
        "LissandraEMissile",
        "LissandraQMissile",
        "LockeQNailMissile",
        "LucianWMissile",
        "LuluQMissile",
        "LuxLightStrikeKugel",
        "MaokaiQMissile",
        "MissileBarrageMissile",
        "MissileBarrageMissile2",
        "NamiRMissile",
        "NautilusAnchorDragMissile",
        "NeekoEMissile",
        "NeekoQMissile",
        "NocturneDuskbringerAura",
        "OlafAxeThrowCast",
        "PantheonQMissile",
        "PhosphorusBombMissile",
        "PoppyRMissile",
        "PykeQMissile",
        "QuinnQMissile",
        "RengarEFinal",
        "RivenWindSlashMissile",
        "RocketGrabMissile",
        "RumbleGrenadeMissile",
        "RyzeQW",
        "SadMummyBandageToss",
        "SejuaniRMissile",
        "SennaWMissile",
        "SeraphineEIsotopeMissile",
        "SeraphineRMissile",
        "SionEMissile",
        "SivirQMissile",
        "SkarnerEIsotopeMissile",
        "SonaRMissile",
        "SorakaQMissile",
        "SwainEMissile",
        "summonersnowball",
        "TahmKenchQMissile",
        "TalonWBlades",
        "TeemoRShroom",
        "ThreshQMissile",
        "UrgotQMissile",
        "UrgotRMissile",
        "VarusQMissile",
        "VarusRMissile",
        "VeigarBalefulStrikeMis",
        "VelkozQMissile",
        "XayahQMissile1",
        "YasuoQ3Mis",
        "YoneQ3Mis",
        "ZeriQMis",
        "ZiggsQSpell",
        "ZiggsQSpell2",
        "ZiggsQSpell3",
        "ZoeEMis",
    };
    for (const char* name : names) {
        if (_stricmp(name, missileName.c_str()) == 0) {
            return true;
        }
    }
    return false;
}

} // namespace Plugins::KuroEvade::Database
